### ISSUE TITLE
Separate APIs for setting HDR mode and LUT file

### ISSUE THREAD

**Issue by chcore** [awawa-dev/HyperHDR#1012]
## Feature request

I think it would be useful to have separate API methods for configuring HDR mode and the current LUT file. I plan to have multiple LUT files depending on the input source/type of content, and this would allow me to change the LUT file without having to find out the current state of HDR mode (which seems to be automatically enabled/disabled by HyperHDR when needed) so that I can include it in a request to "videomodehdr".

#### What problem does this feature solve?

Simpler method of setting a LUT file, without having to know the current HDR mode.

#### What does the proposed API look like?

Changing the "videomodehdr" API so that it excludes the "flatbuffers_user_lut_filename" property, and adding something like a new "lutfilename" command.

#### How should this be implemented in your opinion?

Same as how the other APIs are implemented.

#### Are you willing to work on this yourself?

Unfortunately I am not really a developer, let a lone a C++ developer.

**Comment by awawa-dev** [comment]
I don't see any reason to expand the API with functions that don't bring anything new, arguing only that not to use other API functions. BTW knowing that you use flatbuffers for webOS you need to have tone mapping for these various LUTs ALWAYS enabled: an SDR image processed by webOS is no longer SDR and needs appropriate tone mapping different for SDR and different for HDR (hence several LUTs).

**Comment by chcore** [comment]
What is the difference between these settings?

![image](https://github.com/user-attachments/assets/ca291546-442d-46e2-99fe-81568b3bd499)

![image](https://github.com/user-attachments/assets/52f5b39d-3047-4596-8fe1-07f03e0134b2)

![image](https://github.com/user-attachments/assets/2abd8652-9e88-46e3-84bd-791069f897de)

**Comment by awawa-dev** [comment]
In grabber/flatbuffers settings you enable support for tone mapping at all. Later it can enable/disable via state in the remote tab but for flatbuffers you cannot enable tone mapping if it's disabled in the flatbuffer configuration.

**Comment by chcore** [comment]
> BTW knowing that you use flatbuffers for webOS you need to have tone mapping for these various LUTs ALWAYS enabled: an SDR image processed by webOS is no longer SDR and needs appropriate tone mapping different for SDR and different for HDR (hence several LUTs)

If that's the case, how do I stop HDR from being toggled off automatically when the TV switches from HDR -> SDR?

**Comment by awawa-dev** [comment]
Please ask the question on webOS discord channel, probably you must have properly named LUT tables in the directory and webOS backend will switch them (SDR,HDR,DV) without disabling tone mapping.

**Comment by chcore** [comment]
> Please ask the question on webOS discord channel, probably you must have properly named LUT tables in the directory and webOS backend will switch them (SDR,HDR,DV) without disabling tone mapping.

Will do. If it is relevant, I have HyperHDR running on an RPI. Only the grabber is running on webOS.

**Comment by awawa-dev** [comment]
I think it's no big deal: controlling HyperHDR tone mapping via API doesn't matter if the address is localhost or some other IP on the network. The only difference is the inability to use local sockets to send the image, which bypasses the network interface and it only works when both services are running on the same unit.

**Comment by chcore** [comment]
I named my LUT files "lut_lin_tables.3d" and "lut_lin_tables_hdr.3d" for SDR and HDR respectively (going by the source code).

HyperHDR correctly loads the HDR LUT and enables tone mapping when the TV switches to HDR mode. When the TV switches back to SDR mode, it correctly loads the SDR LUT but also disables tone mapping. Will get on Discord tomorrow

**Comment by chcore** [comment]
> webOS backend will switch them (SDR,HDR,DV) without disabling tone mapping.

After a quick look at the hyperion-webos code (set_hdr_state), seems like it intentionally disables tone mapping when SDR is detected.

**Comment by awawa-dev** [comment]
Did you follow their guide? https://github.com/satgit62/Ultimate-HyperHDR-Ambilight-fine-tuning-experience-for-LG-webOS-with-new-LUT-calibration-?tab=readme-ov-file If so they have a bug for SDR mode.

**Comment by chcore** [comment]
> Did you follow their guide? https://github.com/satgit62/Ultimate-HyperHDR-Ambilight-fine-tuning-experience-for-LG-webOS-with-new-LUT-calibration-?tab=readme-ov-file If so they have a bug for SDR mode.

Just the parts that were up to date. There is some text on that page that aligns with my observations:

> When returning to an SDR video, the HDR (global) mode is automatically switched off and the SDR LUT (lut_lin_tables.3d) is requested.

**Comment by awawa-dev** [comment]
I agree. In their code:
```
    DynamicRange range = get_dynamic_range(hdr_type_str);
    int ret = set_hdr_state(service->settings->unix_socket ? "127.0.0.1" : service->settings->address, RPC_PORT, range);
```
DynamicRange::SDR is zero so it's false.
