### ISSUE TITLE
Frambuffer capture in Ubuntu 24.04

### ISSUE THREAD

**Issue by Pijuli** [awawa-dev/HyperHDR#1015]
First of all. I'm new to HyperHDR, so I might be doing anything stupid and not realizing. That being said ->

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

https://pastebin.com/T64S08Kb

#### Steps to reproduce
Install by the repository method in Ubuntu 24.04
Check a error is raised when starting the service in the UI
Could not open the framebuffer device: '/dev/fb0'. Reason: Permission denied (13)"
Fix permissions with
"sudo adduser $USER video"
Start the service again

I can read some lines about X11 but I can confirm that I am running wayland with
echo $XDG_SESSION_TYPE

#### What is expected?
To work properly

#### What is actually happening?
Nothing. Plain black capture
![image](https://github.com/user-attachments/assets/1e209607-087b-4815-b076-32bd2e828f1f)

#### System

HyperHDR Server: 
- Build:           (HEAD detached at v21.0.0.0beta1) (Awawa-44cfc99/b125da9-1733427229)
- Build time:      Dec  5 2024 19:36:11
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         21.0.0.0beta1
- UI Lang:         auto (BrowserLang: es)
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Ubuntu 24.04.1 LTS
- Architecture:   x86_64
- CPU Model:      12th Gen Intel(R) Core(TM) i5-1235U
- CPU Type:       154
- Kernel:         linux (6.8.0-50-generic (WS: 64))
- Qt Version:     5.15.13
- OpenSSL:        OpenSSL 3.0.13 30 Jan 2024
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by awawa-dev** [comment]
Hi
You must start HyperHDR as an application, not as a service, to make a HyperHDR's Wayland grabber work.

**Comment by Pijuli** [comment]
Ok, that did it. Then, why after installing it tells you to start the service?
That lead me to the wrong path and I didn't even try to find if there was an application. I mean, I could get into the UI 🤷‍♀️

![image](https://github.com/user-attachments/assets/5fd7ebc4-2cc6-4e21-bf38-8de048d949fb)

**Comment by awawa-dev** [comment]
Well, not every one needs Wayland grabber so it's possible run it as a service just as you did it. But the installer makes a suggestion not to enable it and it creates a Windows menu to start the application using it. Also you can add a shortcut to the autostart if you like.
From what I've heard, it's theoretically possible to run the Wayland grabber as a service (you need to add a switch to force the Wayland grabber to HyperHDR, run the app with /? and you'll see them) but then you need to configure permissions in Portal configuration file. I didn't manage to do that, maybe the documentation was poor or I couldn't find the right chapter. But of course experiments are always welcome as long as they lead in the right direction and users share the results ;-)
