### ISSUE TITLE
Home Assistant and MQTT are missing from the controller type dropdown

### ISSUE THREAD

**Issue by DrazorV** [awawa-dev/HyperHDR#1027]
![image](https://github.com/user-attachments/assets/5ae70ca6-f05b-4b6d-bf44-27cb1e3117fc)
As you can see, I don't have the option.
I am running latest version:
![image](https://github.com/user-attachments/assets/d9d309f5-8e13-4344-ad9e-dc45d0d365a4)

and I have already setup the mqtt:
![image](https://github.com/user-attachments/assets/ca4d6139-6a45-49e3-9d75-84055572f195)

**Comment by awawa-dev** [comment]
Hi
These features were added recently after v21beta1 release. Use developers installers from the Github Action tab.
