### ISSUE TITLE
Blackbar detection requires higher threshold when HDR tonemapping is enabled

### ISSUE THREAD

**Issue by peskdale** [awawa-dev/HyperHDR#116]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

Log - https://pastebin.com/aaifWJZd
Config - https://pastebin.com/tn4gM8Jp

#### Steps to reproduce
Enable blackbar detection and set a suitable threshold for SDR (or HDR grabbed as SDR) content.

For example, this image requires just 10% threshold to work, despite the poor contrast, and the bars being off-black (15,15,15).
![shot180710](https://user-images.githubusercontent.com/5855217/132135621-a066a471-d53d-460e-9e07-f36f243b3edd.png)

Enable HDR tonemapping. This is the same image after tonemapping has been turned on.
![shot180717](https://user-images.githubusercontent.com/5855217/132135669-c210e533-a3c1-4390-8594-75364794fa31.png)

#### What is expected?
Blackbars should continue to be detected at current threshold level.

#### What is actually happening?
Blackbars are no longer detected. Threshold has to be increased to 16% for them to be detected on the tonemapped image.

This is odd, as there is a greater contrast in the tonemapped image, and the blackbars are true black (0,0,0).

#### System

```HyperHDR Server: 
- Build:           (HEAD detached at 4e4031c) (Awawa-eba222b/4e4031c-1630846534)
- Build time:      Sep  5 2021 13:29:15
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0beta2
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17-v7+ (WS: 32))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 ```

**Comment by awawa-dev** [comment]
Hi
If you zoom the image you will get:
![obraz](https://user-images.githubusercontent.com/69086569/132137013-df6ecb12-12b0-4148-98df-e0fd55ca6d39.png)
It's almost invisible on the first SDR image but HDR processing bump that lines to values around RGB(28,28,28)... looks like the artifact from the movie source or it was introduced by the grabber. If it is permanent you can use cropping to remove that lines at the top.

**Comment by peskdale** [comment]
Ha! Thanks - that's rather embarrassing! Yes, a 3px crop seems to have done the trick. :+1:

**Comment by awawa-dev** [comment]
No problem. Very detailed report with samples 👍  , so it didn't take long.
