### ISSUE TITLE
Inactive SPI in HyperHDR 17.0.0.0 SD card image

### ISSUE THREAD

**Issue by scit2010** [awawa-dev/HyperHDR#121]
Today I installed the HyperHDR 17.0.0.0 SD card image and ran it. 
I configured a WS2801 light strip and the USB grabber and tried some effects. Nothing worked, i.e. all LEDs stayed black.
Then I figured out in the log, that none of the listed SPI sources worked. 
To fix this I logged in through SSH, ran raspi-config, activated the SPI interface and rebooted. This fixed it.
So, as it seems, SPI needs to be activated in your SD card image as it was in version 16.0.0.1.

**Comment by awawa-dev** [comment]
Which architecture?

**Comment by awawa-dev** [comment]
Some things have changed in pi-gen and old scripts needed new workaround for enabling SPI. New images are uploaded now.
