### ISSUE TITLE
Docker image up

### ISSUE THREAD

**Issue by appleimperio** [awawa-dev/HyperHDR#125]
First of all thank you Awawa again for a great job. This version looks amazing, if someone is interested on a Docker image of the latest version (v17) here is the link https://hub.docker.com/r/nocturno/hyper-hdr . This is an AARCH64 docker image. Any problem related to the Docker image or if you prefer to build your own image here is the place https://github.com/appleimperio/docker-hyperhdr.

**Comment by awawa-dev** [comment]
Thanks @appleimperio  👍 
I move it to the Discussion
