### ISSUE TITLE
Failed to update record: 'WHERE user=?'

### ISSUE THREAD

**Issue by felixbro** [awawa-dev/HyperHDR#155]
Full LOG:
https://pastebin.com/LQVzhQun
Config JSON:
https://pastebin.com/CEvxHGrS

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

i was trying to turn on "Automatic signal detection" and after that i only get Error Pop-ups when im saving any settings.
On the next day i was trying to update my WebUI password and now the log keeps saying 'auth' Error.

#### Steps to reproduce
- Turn "Automatic signal detection" on
- Click Save
- next day: try to update default WebUI password
#### What is expected?
- Saving settings
- chaning password
#### What is actually happening?
Pop-up: "ERROR
Save settings failed"
#### System

HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 16:23:59
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63-v7+ (WS: 32))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36

**Comment by awawa-dev** [comment]
please upload your config backup, without it can't help.

**Comment by felixbro** [comment]
ok, here it is:
[https://pastebin.com/CEvxHGrS](https://pastebin.com/CEvxHGrS)

**Comment by awawa-dev** [comment]
Thank you.
Still, can't reproduce the problem.
![obraz](https://user-images.githubusercontent.com/69086569/142169843-51ee83d5-6aaf-4e10-b561-c61bf9946567.png)
![obraz](https://user-images.githubusercontent.com/69086569/142169860-5b515921-e5c4-4fb8-86c0-7c234f621bcd.png)
![obraz](https://user-images.githubusercontent.com/69086569/142169880-cddbe94b-81c6-457f-a06f-0ca045cc511e.png)
![obraz](https://user-images.githubusercontent.com/69086569/142169897-36717bd9-366c-4e3c-b1f1-807e8713a793.png)

**Comment by awawa-dev** [comment]
I think the main problem is in the auth table that is not backup due to security reasons:
````2021-11-17T08:25:15.940Z [DB] Failed to update record: 'WHERE user=?' in table: 'auth' Error:  
2021-11-17T08:25:15.977Z [DB] Failed to update record: 'WHERE user=?' in table: 'auth' Error:  
2021-11-17T08:25:15.985Z [DB] Failed to update record: 'WHERE user=?' in table: 'auth' Error:  
2021-11-17T08:26:07.878Z [DB] Failed to update record: 'WHERE type=?' in table: 'settings' Error:  
2021-11-17T08:30:56.037Z [DB] Failed to update record: 'WHERE user=?' in table: 'auth' Error:  
2021-11-17T08:30:56.053Z [DB] Failed to update record: 'WHERE user=?' in table: 'auth' Error:  ````
guess the config was imported from older hyperhdr or some other application (where hyperhdr user doesn't exists). Unfortunately can't reproduce it and without can't change anything. Your backup file works just fine without errors on my system after the import so I guess  export/import can be a workaround for fixing broken configs in specific cases. If you can provide path that can be reproduce on new setup feel free to re-open it.
