### ISSUE TITLE
Capture Card gets killed on HyperHDR Boot

### ISSUE THREAD

**Issue by iblake12** [awawa-dev/HyperHDR#157]
https://pastebin.com/9SQYSrRG

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

https://pastebin.com/9SQYSrRG

#### Steps to reproduce
Start up HyperHDR on Raspberry Pi 3B+ running Pi OS Lite

#### What is expected?
Capture card feed to be visible in live video window and capture card loop out to show on TV

#### What is actually happening?
As soon as HyperHDR loads (and the LEDs play the startup effect) the loop out on capture card goes blank and no video is shown in webpage live video window.
Capture card shows up as an option and is selectable.
Have tried with different capture cards, hdmi cables and USB cables, powering card externally and via the Pi. Same issue every time

#### System

HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 16:23:59
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi 3 Model B Plus Rev 1.3
- CPU Revision:   a020d3
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63-v7+ (WS: 32))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

**Comment by awawa-dev** [comment]
And what makes you thing it's a HyperHDR issue not your video grabber/capture card? That short logs looks clear to me (too short to detect if the V4L2 captured something).

**Comment by awawa-dev** [comment]
Well that single last line is few minutes after...your capture card is simply not working.

**Comment by iblake12** [comment]
Hi, thanks for the fast reply! I have tried 4 different capture cards all producing the same problem, all of them pass through fine if i unplug and replug them into the Pi (so they get power but not communicating with hyperhdr), and they also work fine on the Pi booting for passthrough until hyperhdr loads. I am using the same capture card as a few other people with the same hardware and they dont seem to have an issue, have also had a couple people more confident with your software have a look and couldnt figure out the issue, they suggested i come here to ask after they tried everything they could think of.
