### ISSUE TITLE
Internal grabber support

### ISSUE THREAD

**Issue by hissingshark** [awawa-dev/HyperHDR#161]
Hi,

I got here from the closed PR for HDR tone mapping on the Hyperion.ng repo.

From what I can tell the internal grabbers such as Amlogic/FB have been dropped in this fork.
Is that correct i.e. USB grabbers only?

**Comment by awawa-dev** [comment]
Hi
There are 3 internal grabbers for now: X11(Linux)/AVF(macOS)/DirectX11(Windows). Don't have any Linux/Amlogic device now so can't support it. So it leaves only USB option.
