### ISSUE TITLE
Hardware not supported - raspberry pi zero 2W

### ISSUE THREAD

**Issue by trivi** [awawa-dev/HyperHDR#168]
I confirm that this is an issue rather than a question.

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
Full log: [https://pastebin.com/hZAC77Rz](url)
As additional information hyperion had the same issue and it seems to be fixed in the latest nightly (not tested by myself, HDR is a must for me): https://issueexplorer.com/issue/hyperion-project/hyperion.ng/1367

#### Steps to reproduce
Fresh install of HyperHDR 17.0 using WS2812b led strip and ws281x Controller type.

#### What is expected?
LED strip light up while "RGB order wizard" is running

#### What is actually happening?
Getting error: [LEDDEVICE] Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: Hardware revision is not supported'

#### System
HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 16:21:00
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         auto (BrowserLang: es-ES)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi Zero 2 Rev 1.0
- CPU Revision:   902120
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.63-v8+ (WS: 64))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

**Comment by awawa-dev** [comment]
Hi
First of all: as it's stated in the FAQ direct usage of LED strip from Raspberry Pi is not officially supported anymore so I don't consider it as HyperHDR issue but limitation of rpiws1x library model... need of rpiws821x developers to chase new models Rpi is just one of many reasons (other are more serious). I just leave it for backward compatibility, but will try to update rpiws821x library before next release. So please be patient.

**Comment by trivi** [comment]
Hi, 
in case it helps anyone else, I built the current version in the master branch (version 18.0.0.0beta1/c8049f1 hash) and it is working like a charm. 

Thank you!
