### ISSUE TITLE
HyperHDR as a Deb 

### ISSUE THREAD

**Issue by Bboy486** [awawa-dev/HyperHDR#17]
Backup my current hyperion config and import into hyperhdr while installing as a systemd service on a retropie image?

RPi4 - Retropie

LEDs - https://www.amazon.com/dp/B01CDTEJBG?ref=ppx_pop_mob_ap_share
Power - https://www.amazon.com/dp/B0852HL336?ref=ppx_pop_mob_ap_share

USB capture - https://www.amazon.com/dp/B07Z7RNDBZ?ref=ppx_pop_mob_ap_share

Splitter - https://www.amazon.com/dp/B08D9BCX1R/ref=cm_sw_r_cp_apa_fabc_Sj43FbWHRFEQG

**Comment by awawa-dev** [comment]
Config import should work, HyperHDR deb installers uses systemd services as default with systemctl to control it. However I'm not familiar with retropie at all. You can also create the service manually and point it to /usr/bin/hyperiond if the installer faills.
Dont know that USB grabber. RGBW sk6812 could be also considered in place of RGB WS2812b.
I would order also Esp8266 wemos d1 mini and at least one 1N400x diode for level shifter 3.3V->5V.

**Comment by Bboy486** [comment]
Why would I need the level shifter?

**Comment by awawa-dev** [comment]
Rpi4 and Esp8266 has 3.3V logic level and LED strip 5V or something around this value. May work or not... I mentioned that subject more precisely on the latest post on my blog.

**Comment by Bboy486** [comment]
Got it. 

Well with my setup I now have 4K on the shield/pc and hyperhdr works. HDR to SDR tone mapping when enabled messes the colors up bit I'm not sure what that does.
