### ISSUE TITLE
Add Dependencies to packaged releases

### ISSUE THREAD

**Issue by pewter77** [awawa-dev/HyperHDR#18]
## Feature request
Add in Dependencies into deb files

#### What problem does this feature solve?
Makes sure that the linux distro has the correct files needed (in my case docker) when installing
#### What does the proposed API look like?
n/a
#### How should this be implemented in your opinion?
n/a
#### Are you willing to work on this yourself?
I can, I think it's an easy pull request but I don't want to break anything on your side as I'm actually not a developer
I had to install **ibusb-1.0-0 libexpat1 libglu1-mesa libglib2.0-0 libfreetype6** these manually (when I created my docker image). Would simplify everything if I could avoid that step and simple apt install -y hyperhdr.deb file!

This might just be me not completely understanding everything though and maybe these dependencies are different on other debian systems?

**Comment by pewter77** [comment]
Two more things:

1. Not saying to include these but just have them included as dependencies so they are automatically grabbed
2. xz-utils is also needed (missed it before but it's for the LUT tables?)

Cheers!

**Comment by awawa-dev** [comment]
Hi
Thanks for the info! Yes, xz-utils is needed to decompress packed LUT table as without it that file has 150MB (and around 7MB packed with xy). The next version is almost finished while we still testing it but I'll include it in next maintenance release soon after. We are talking about deb for x64 Linux system of course? I must check that dependencies as once adding libCEC caused all non-x11 system to broke down (the cause was not directly libCEC but one of libraries that libCEC depends on).
Best regards :)

**Comment by pewter77** [comment]
yes currently it's for x64 linux system, I'd like to do a 2 phase docker approach where I build the deb file and then copy it over into the actual docker image, but I think right now I'm a bit out of my league in this respect. I can build the source currently but it leaves the docker image far too big and I'm not sure how to actually package deb files.

The xy-utils thing makes sense but the deb file doesn't error out or fail installation, some people might not even realize they didn't get the LUT tables at all!

**Comment by awawa-dev** [comment]
Yes, you've got the point. xz-utils are critical part for the installation although there are always errors/warning in the debug log about missing LUT file. And LUT table can be generated later on the page. But I agree it should be solved by making  xz-utils necessary for the process installation. Will try to change it in the incoming release at least for x64 deb.

**Comment by awawa-dev** [comment]
After some tests it seems that libusb-1.0-0 libexpat1 libglib2.0-0 libfreetype6 xz-utils are already present in the minimal distro of Rasbpian so I included them as dependency. 
libglu1-mesa is another story...it would cause massive ~500MB installation of packages and I can only suspect that users would lynch me ;) On Rpi libglvnd0 (already as dependency) takes its role as a stub.
Changes already included in just released version v14.

**Comment by awawa-dev** [comment]
One of missing libglu1-mesa's library that HyperHDR depends on is now included in the installer/archive in version 15. So I think that's all now.
