### ISSUE TITLE
Orbi, HyperHDR, PiHole

### ISSUE THREAD

**Issue by Bboy486** [awawa-dev/HyperHDR#181]
I am having an issue when I use HyperHDR (RPi4, 4K Capture Card, Denon AVR) where it will interfere with my Orbi Router and knock the wifi offline. I know it is HyperHDR as I just did a new install on the same pi as my Pihole and the internet went down. I do not know where to start troubleshooting but the logs are attached. 
Happy to share anything else but wanted to open this up to see what is happening. 
[HyperHDR Logs.txt](https://github.com/awawa-dev/HyperHDR/files/7817829/HyperHDR.Logs.txt)

Additionally setting LED hardware instance to disabled restores wifi.

**Comment by awawa-dev** [comment]
Hi
Unfortunately can't help with network related problems especially when network is especially pihole domain. Maybe you set some ports in pihole configurations that are used by HyperHDR on default: 8090 or 8092? BTW also your grabber doesn't work judging from  your logs but symptoms are typical for some video capture devices when no HDMI sources are available.

**Comment by Bboy486** [comment]
> Hi Unfortunately can't help with network related problems especially when network is pihole domain. Maybe you set some ports in pihole configurations that are used by HyperHDR on default: 8090 or 8092? BTW also your grabber doesn't work judging from your logs but symptoms are typical for some video capture devices when no HDMI sources are available.

I have the grabber working but it only works on automatic and I can no longer set the dimensions on beta.

**Comment by Bboy486** [comment]
[New logs_220106_210156.txt](https://github.com/awawa-dev/HyperHDR/files/7826268/New.logs_220106_210156.txt)

**Comment by awawa-dev** [comment]
The logs are cut off i don't like it. Anyway I see that when you connect the HDMI source the grabbed started to work: just as I wrote. Still can't see any problem with the network or the grabber in logs you provided.

**Comment by Bboy486** [comment]
Ok. Thanks. I have other issues however. Should I open a new issue or can I post here?

**Comment by awawa-dev** [comment]
you can post it here and i can take a look.

**Comment by Bboy486** [comment]
I uploaded new logs after a restart (but have no run actual video). 

1. Where is the option to calibrate RGB GRB? I no longer see it. 
2. I have an issue where whites and sandy browns when solid on the frame show was red. I have messed with settings to see what is causing this but haven't found the issue.
3. For my [Grabber ](https://www.amazon.com/gp/product/B08MPPKZ55/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) I have to select automatic as the two entries when selected do not work. This is since I upgraded to v17.0.0.0 as well as v17.0.0.0 Beta. Additionally, when I pick automatic I can no longer change the device resolution (which has helped in the past with issues. (1280 x 720). 
4. I am using ws281x with GPIO pin 12 (GPIO 18). I am told using ground will help but does it matter if the ground is pin 5 or 14? does it matter if I use the left most or right most input on the led for ground? The middle goes to pin 12. 


[Fresh Start-up Logs.txt](https://github.com/awawa-dev/HyperHDR/files/7833995/Fresh.Start-up.Logs.txt)
[HyperHDR-17.0.0.0beta-Backup-2022-01-08.txt](https://github.com/awawa-dev/HyperHDR/files/7833997/HyperHDR-17.0.0.0beta-Backup-2022-01-08.txt)

**Comment by awawa-dev** [comment]
Hi
1) you can find it in one of sub-menus in the advanced tab
2) hard to say, the problem could be in the grabber itself, its configuration (hardware brightness/hue/saturation settings were changed), wronf calibration in the image processing tab etc..does the problem with colors appear in the live video window? probably it's best to start from fresh settings deleting old settings and restart the system.
3) that's what I see in the logs and it's not HyperHDR issue, probably other software use it or it's some kind of driver/device malfunction, again your grabber doesn't work at all:
2022-01-08T20:38:17.536Z [V4L2:AUTO] Found capture device: /dev/video14
2022-01-08T20:38:17.536Z [V4L2:AUTO] Found capture device: /dev/video15
2022-01-08T20:38:18.395Z [V4L2:AUTO] Throws error nr: **Cannot open '/dev/video0' error code 16, Device or resource busy** 

4) driving ws281x led strip is not longer officially supported. Anyway in the logs the LED device is working. If there is not reaction from the LED strip there could be multiple reason: fried GPIO section, some kind of problem in the electrical installation, missing 3.3V to 5V level shifter,

**Comment by awawa-dev** [comment]
It doesnt matter which ground pin you use but pin 5 is NOT the ground.

**Comment by awawa-dev** [comment]
And just to be clear: ground from Rpi should be connected to 'minus' of the power supply that provides power for LED strip (absolutely NOT it's ground). Example: https://github.com/awawa-dev/HyperHDR/discussions/182#discussioncomment-1920409

**Comment by Bboy486** [comment]
> It doesnt matter which ground pin you use but pin 5 is NOT the ground.

Sorry Pin 6 - https://cdn.sparkfun.com/assets/learn_tutorials/1/5/9/5/GPIO.png
