### ISSUE TITLE
Support for PicCap (LG TV picture stream) App 

### ISSUE THREAD

**Issue by sorted01** [awawa-dev/HyperHDR#197]
## Feature request

Hi awawa! 

#### What problem does this feature solve?
Receiving the picture which is streamed via flatbuffer from the PicCap App on LG TVs 

#### What does the proposed API look like?
I don't know :D

#### How should this be implemented in your opinion?
So hyperhdr offers flatbuffer but somehow the image is not received. Once I use standard hyperion the streaming works fine out of the box. Maybe just activate flatbuffer in hyperhdr? 

#### Are you willing to work on this yourself?
Yes. And of course I would try to support :)

Thank you!

**Comment by awawa-dev** [comment]
HyperHDR flatbuffer definitely works with piccap as some user use it & they confirmed it ;) Configuration or network issue.

**Comment by sorted01** [comment]
Thank you for the super fast feedback! As always!
Then I'll do a clean setup of HyperHDR and give it another try.
