### ISSUE TITLE
Can't edit the text field for coordinates  under LED Layout

### ISSUE THREAD

**Issue by luchow3cu** [awawa-dev/HyperHDR#235]
#### Steps to reproduce
Edit the text field for the LED coordinates under LED Layout Tab
#### What is expected?
Edit the values for hmax, hmin, vmax, vmin and save new layout
#### What is actually happening?
The cursor jumps continuously to the beginning of the text field, you can't edit nor select the text because the of this gui bug
#### System
HyperHDR Server: 
- Build:           (HEAD detached at ead6db4) (Awawa-dda6207/ead6db4-1645993537)
- Build time:      Feb 27 2022 20:34:47
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0beta1
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 4 Model B Rev 1.4
- CPU Revision:   c03114
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.92-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15 

https://user-images.githubusercontent.com/49795210/156402461-2e4aec29-1fbc-43e5-a264-333cd3e6ac1f.mp4

**Comment by awawa-dev** [comment]
Fixed
