### ISSUE TITLE
Install HyperHDR on Home Assistant OS

### ISSUE THREAD

**Issue by ihrapsa** [awawa-dev/HyperHDR#245]
#### What problem does this feature solve?
Not being able to run HyperHDR server on the same device running HomeAssistant OS
#### What does the proposed API look like?
N/A
#### How should this be implemented in your opinion?
Through the Home Assistant Add-on Repository. The Hyperion.ng project was (fairly)recently added so we might look into [that](https://github.com/bradsjm/hassio-addons) as an example.
#### Are you willing to work on this yourself?
I'm not sure I have the necessary skills for that but I'd be more than happy to help and/or test.

**Comment by awawa-dev** [comment]
Hi
Personally don't use HA and I highly doubt there are enough resources free on the Rpi when HA is running. When I tested HA on Rpi3, there weren't enough resources even for HA running solo on the device and the interface lag was terrible. Maybe on Rpi4 with more available RAM the situation is better, don't have s spare unit to test it. I don't plan on making such a plugin, but maybe some other users would create it as a separate project.

**Comment by ihrapsa** [comment]
I've actually managed to get HyperHDR up and running today as a [hass add-on](https://github.com/ihrapsa/hassio-addons) on a pi4b  with 4gb RAM and don't see any issues yet. Will do some performance tests tomorrow. 
I've followed the [Hyperion.ng template](https://github.com/bradsjm/hassio-addons) I was talking about above so it might be a little sloppy but if someone more competent then I wants to contribute to this I'm more than happy to approve PRs. 😃

**Comment by awawa-dev** [comment]
If the performance is satisfied then I can provide link on HyperHDR to your fork. Same as it's done for @mjoshd and his HA plugin for HyperHDR. Do you have an access to CPU/RAM statistics when HyperHDR is running and capturing video and how they look like? They are also available in v18beta in the overview tab if there is no direct access to the system.

**Comment by ihrapsa** [comment]
Hi, CPU and RAM usage are minimal while capturing as far as I can tell (CPU 4.7-6.1%, RAM ~2%) on this pi4B 4GB. However, I'm having issues with flickering. I'm using wled to drive the strip but the flickering happens only when hyperhdr drives the strip. Any idea what might cause this? 

What I've tried: 
  - 2 different capture cards - no change
  -  changing capturing fps and resolution -no change
  - enabling/desabling smoothing - if disabled flickering becomes more noticable
  - changing video source (**Chromecast with google tv** and **xiaomi mi box**) - no change
 
I've also installed HyperHDR on a separate pi3B+ with the same wled driver and psu and there's no flicker/issues

![image](https://user-images.githubusercontent.com/40600040/158689094-831c2f52-6d6d-4c0d-9e43-d6765ae269b8.png)
![image](https://user-images.githubusercontent.com/40600040/158690940-d41200c8-7777-4005-96fe-71eba7416b9c.png)

**Comment by awawa-dev** [comment]
> Ok something weird fixed this. I have two identical hdmi capture cards and I was planning to test the working capture card from the pi3b on the pi4b. After I plugged it out from the pi3b the flicker on the other TV (where the pi4b sits) disappeared. I think HyperHDR on the pi3b was still trying to control the wled driver (as I have only one at the moment).

Yes, that's possible that these two units were fighting for the same WLED device. WLED UDP driver is rather ugly and it won't notify user about any trouble. Unfortunately not much can be done here because QT libraries won't throw any error even if the WLED device is powered off (at least for Windows, for Linux it depends).

**Comment by ihrapsa** [comment]
Hi, I've rebuilt the different arch docker images thanks to [bradsjm](https://github.com/bradsjm/hassio-addons/blob/master/.github/workflows/addon-hyperion-ng.yml)'s scripts and workflow and I think the add-on is ready now. I did some further testing and I see no difference compared to a standalone installation. 🙂

**Comment by awawa-dev** [comment]
Great! I will provide info about your fork with the next release of HyperHDR and invite everybody to help with testing :)

**Comment by FransTwisk** [comment]
This is great! Was already running Home Assistant (Supervised) with a manual install of HyperHDR next to it, but this would make it easier to maintain and update. Just switched, imported config and works fine. I might even switch to Home Assistant Operating System now!

**Comment by ihrapsa** [comment]
> This is great! Was already running Home Assistant (Supervised) with a manual install of HyperHDR next to it, but this would make it easier to maintain and update. Just switched, imported config and works fine. I might even switch to Home Assistant Operating System now!

I'm really glad you found it useful.

I might just close this as well since the issue is solved.
