### ISSUE TITLE
Unable to change/save any settings

### ISSUE THREAD

**Issue by Coolie1101** [awawa-dev/HyperHDR#248]
#### Logs
https://pastebin.com/dqTt603u

#### What is expected?
Change update LED settings based on my install.

#### What is actually happening?
I am not able to save any settings/changes made, save button does not accept any input, can't even change the default password.

#### System
HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 16:19:40
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        ready-only

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.17+ (WS: 32))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46

![image](https://user-images.githubusercontent.com/28989417/160221772-e5bceeff-832d-4963-89aa-e96e7568c130.png)

**Comment by awawa-dev** [comment]
Sorry, unable to reproduce (tested on v18beta). Saving also works fine. Try to delete you old settings and start from the scratch because maybe configuration database is broken (import from other application/version?)
![obraz](https://user-images.githubusercontent.com/69086569/160222641-f0f9e66a-60e6-4b1c-8c7a-f84604b7ac08.png)

![obraz](https://user-images.githubusercontent.com/69086569/160222764-9e25a9cf-b498-49fc-9eb1-377b9a579902.png)

**Comment by Coolie1101** [comment]
> that method is not officially supported

Can you please elaborate on this, I'm not sure I understand.

**Comment by awawa-dev** [comment]
There are too much problems and it also affects the overall performance of the system so driving LED strip directly from RPi  (especially without a voltage level shifter) is not officially supported by HyperHDR. Still, that option is left enabled for advanced users if they what to use it anyway and they are able to diagnostic the system (both software and hardware) if something goes wrong.  
Back to your problem, in your logs:  
```readonlyMode = enabled```  
You've got the OS file system in the read-only mode so HyperHDR interface won't you allow to save any changes anyway...

**Comment by awawa-dev** [comment]
Or lack of the write privilege for the user that runs HyperHDR for the file: '/.hyperhdr/db/hyperhdr.db'
