### ISSUE TITLE
Limit fps by code

### ISSUE THREAD

**Issue by luci-11** [awawa-dev/HyperHDR#25]
## Feature request
Premise: this project works great!
Do you think it could be possible to have an option to limit fps by code? Obv if you think this can be useful for less powerful installation..
I have I pi zero w and a mjpeg grabber. I know ..bad couple .. but I need to say that for a not-so-choosy installation is more than just 'ok'.
The mjpeg grabber only has 60 and 30 fps as options. Resolution is at its minimum so 640x480.
Maybe discarding the processing of some frames (like to 20fps) could stress a little bit less the pi and reduce latency a little bit without impacting too much the whole experience...
What do you think?

#### What problem does this feature solve?
Better compatibility for Pi zero w and mjpeg grabber 

#### What does the proposed API look like?
-

#### How should this be implemented in your opinion?
A flag on the interface that does not change directly grabber fps but just the number of processed frames

#### Are you willing to work on this yourself?
Not capable unfortunately 😔

**Comment by awawa-dev** [comment]
It's already implemented as I faced the same problem before: 'software frame skipping' in the grabber properties ;)

**Comment by luci-11** [comment]
Wow, sorry I didn't noticed it!
Thanks a lot for reply. Tomorrow I'll give it a try 😃

**Comment by luci-11** [comment]
Closing issue as already implemented
