### ISSUE TITLE
SD-card-image-rpi012-armv6 does not run hyperHDR

### ISSUE THREAD

**Issue by erganmedia** [awawa-dev/HyperHDR#251]
Hi, I just downloaded the prebuild image for the Raspberry Pi zero (SD-card-image-rpi012-armv6.zip). I am using a Raspberry Pi Zero WH. I used Raspberry Pi Imager to flash the image to the Pi. Everything seems to work. I can connect to the Pi via ssh but there is nothing running on port 8090. I checked htop and I assume that hyperHdr isn't even running
<img width="1353" alt="Bildschirmfoto 2022-04-05 um 15 12 10" src="https://user-images.githubusercontent.com/18619741/161761787-88c2b881-aa11-4d7f-aa49-fa464af27aa4.png">

Do you know what went wrong?

**Comment by erganmedia** [comment]
hyperhdr was installed, but the service wasn't running. I had to create a service and run it on boot. The Raspberry Pi Images allows you to create a default user for the OS, which in my case was not "pi". Maybe this was the cause of my problem.

anyways. It works now

**Comment by awawa-dev** [comment]
SD card images have hardcoded startup service for pi user. DEB installers should detect your current user even if the 'sudo' is used for the installation. Anyway I'm happy that it works now.
