### ISSUE TITLE
Lut file not loaded

### ISSUE THREAD

**Issue by appleimperio** [awawa-dev/HyperHDR#26]
(WARNING) setHdrToneMappingMode to: enable, but the LUT file is currently unloaded
 
I place the generated lut file in the .hyperion Config folder. I’m not sure if that’s the correct path. Any idea?

**Comment by awawa-dev** [comment]
Please post all the log after restart: the path is there.

**Comment by awawa-dev** [comment]
Also that warning may appear short after start when the hyperhdr config is read. But next in the log you should see when the LUT table is loaded after grabber driver initialization.

**Comment by appleimperio** [comment]
I forced the encoding for yuv and it load perfectly. Is there any difference between using the WLED vs the WLED serial interface? Thanks Awawa for the great work

**Comment by awawa-dev** [comment]
Thanks!
If you want to have a minimal lag and perfectly stable connection from ESP to LED strip then WLED serial at 2000000 is the way to go. If you want to reduce some cables then wifi: lag could be a little bigger and there could be some issues related to wifi signal stability.
As you can see even with a strong signal there some troubles with a continues transmission over wifi:
https://i.postimg.cc/j2srNMDR/s1.jpg
On the other hand when using USB serial port, the transfer is almost perfectly constant: 
https://i.postimg.cc/W35bxNGz/250-rgb-setup.jpg
