### ISSUE TITLE
HDR to SDR tone mapping via protocol buffers

### ISSUE THREAD

**Issue by flos06** [awawa-dev/HyperHDR#263]
## Feature request

HDR to SDR tone mapping is available via flatbuffers. I would like to use it via proto buffers

#### What problem does this feature solve?

My grabber can only use proto buffers

#### Are you willing to work on this yourself?

I would love to if I knew how

**Comment by awawa-dev** [comment]
I see that hyperion-android-grabber developers successfully defend their self against flatbuffer implementation ;) And it would require a lot less of work than duplicating behavior of flatbuffer (it supports hdr tone mapping) in HyperHDR. Personally I'm not interested in supporting Hyperion's apps but I think it wouldn't be a great challenge to swap protobuf for flatbuffers in that app. Protobuf currently is on it's way out and probably it will be removed in the next version.

**Comment by flos06** [comment]
> I see that hyperion-android-grabber developers successfully defend themselves against flatbuffer implementation ;) And it would require a lot less of work than duplicating behavior of flatbuffer (it supports hdr tone mapping) in HyperHDR. Personally I'm not interested in supporting Hyperion's apps but I think it wouldn't be a great challenge to swap protobuf for flatbuffers in that app. Both are well supported by Google. Protobuf currently is on its way out and probably it will be removed in the next version.

Yes I have indeed asked over there if they would be willing to implement flatbuffers. I would like to give it a shot myself, but unfortunately I only have a very rudimentary understanding of programming and 0 experience with either flatbuffers or protobuffers. I can change the scheme around but thats about it. I'll try to read up about both to see if I can maybe hack something together myself. But I'm not giving myself a lot of chance unfortunately.
Anyways. Thanks for your amazing work and for your reply.

**Comment by awawa-dev** [comment]
I found a fairly simple workaround how to redirect protocol buffers stream to flatbuffer instance for HDR tone mapping.
Let me know it it works also on your system.

**Comment by flos06** [comment]
I will try this tomorrow! Thanks for your effort!

**Comment by flos06** [comment]
I can confirm this works on my system! Thank you very much for implementing this.
One more question. Am I correct in understanding it works for HDR10 but not for Dolby Vision? (I don't really mind just wondering if I have to take it into account when choosing a video source)

**Comment by awawa-dev** [comment]
HDR10 for sure. Are you able to capture Dolby Vision? Support for proper capturing this format is almost none and I've heard just about one limited success (captured image far from perfect) which used TV apis but it's not available anymore with newer firmware. Even HDFury dive handles LLDV.

**Comment by flos06** [comment]
I mean it captures an image. However the colors are inaccurate. I.e. Red becomes purple.
It was the same for HDR10 prior to your latest commit which fixed the inaccuracies with HDR10, but not for DV.

**Comment by awawa-dev** [comment]
If the DV image is all purple then it's not properly captured and damaged. Otherwise you can experiment with creating your own LUT table to fix colors.

**Comment by flos06** [comment]
It's not all purple, but there is a lot of purple. Probably not properly captured. I'm happy with HDR10 though :) 
Would HDR10+ give the same issues as DV?

**Comment by awawa-dev** [comment]
Hi @flos06 
Could you test the version from the latest build? Installers are here: https://github.com/awawa-dev/HyperHDR/actions/runs/2387646416
I migrated from protobuf libraries to nanopb and that little library handles now the protobuffer stream. Tested with DirectX Screen Grabber and it works for proto after the migration. So it leaves only hyperion-android-grabber for testing. If everything will be OK then protobuf server could stay in HyperHDR as nanopb is much nicer and lightweight.

**Comment by flos06** [comment]
Hi,
I will have time to test sometime this week and will let you know the result :)

**Comment by flos06** [comment]
Unfortunately at the moment my LEDS do not light up at all. Doesn't seem to be a power supply issue so it may be that my LED strip has died. Trying to figure it out. But will not be able to test for a while if the LED's are actually dead

**Comment by awawa-dev** [comment]
No problem. I've managed to already test it using one old Android device.

**Comment by flos06** [comment]
a bit late, but I can confirm this works thanks :)
