### ISSUE TITLE
Upgrading to V17 to 18 Beta - service will not start

### ISSUE THREAD

**Issue by Bboy486** [awawa-dev/HyperHDR#269]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

I cannot pull logs from the web interface. Is there another way to pull the logs by the command line or where are they saved on the pi?

#### Steps to reproduce
sudo systemctl start hyperhdr@pi.service
go to hyperd:8090 in browser
GUI doesn't launch

 systemctl status hyperhdr@pi.service
● hyperhdr@pi.service - HyperHdr ambient light systemd service  for user pi
   Loaded: loaded (/etc/systemd/system/hyperhdr@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

These were the install steps
sudo wget
https://github.com/awawa-dev/HyperHDR/releases/download/v18.0.0.0beta2/HyperHDR-18.0.0.0beta2-Linux-armv7l.deb

sudo apt install ./HyperHDR-18.0.0.0beta2-Linux-armv7l.deb
SETUP ROOT ACCESS

sudo systemctl stop hyperhdr@pi.service
sudo systemctl disable hyperhdr@pi

create service for root:

sudo systemctl enable hyperhdr@root
sudo reboot

#### What is expected?
Website Loads

#### What is actually happening?

 sudo /usr/share/hyperhdr/bin/hyperhdr -d
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/hyperhdr)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Gui.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libasound.so.2)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libpng16.so.16)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libicui18n.so.67)
/usr/share/hyperhdr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libicuuc.so.67)

#### System

I cannot get into the interface

**Comment by awawa-dev** [comment]
Hi
It's explained here: [LINK TO SOLUTION](https://github.com/awawa-dev/HyperHDR/discussions/262)  
v18.0.0.0beta2 provides also new SD card images.

**Comment by Bboy486** [comment]
I followed that however I still receive this error

Reading package lists... Done
E: The method driver /usr/lib/apt/methods/http/ could not be found.
N: Is the package apt-transport-http/ installed?

Last login: Thu May 12 02:42:50 2022 from 10.6.0.2


pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get full-upgrade
Hit:1 https://download.docker.com/linux/raspbian bullseye InRelease
Hit:2 http://deb.nodesource.com/node_16.x bullseye InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/http/ could not be found.
N: Is the package apt-transport-http/ installed?
E: Failed to fetch http/://raspbian.raspberrypi.org/raspbian/dists/bullseye/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by awawa-dev** [comment]
```sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get full-upgrade```
Where does this command come from exactly?
```E: Failed to fetch http/://raspbian.raspberrypi.org/raspbian/dists/bullseye/InRelease```
You didn't follow the linked article. Pay attention what's its happening in ```http/://``` part.
