### ISSUE TITLE
Green led on dark image

### ISSUE THREAD

**Issue by dawiinci** [awawa-dev/HyperHDR#273]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

I am using HyperSerialEsp8266 (@1Mbps) 7.0.0.0 with neutral white SK6812 and the recommended RULLZ grabber (coffee, blue). Proper LUT is in config folder. 

#### Steps to reproduce
Display dark color in non hdr. 
#### What is expected?
Led should be darker or off. 
#### What is actually happening?
Led are green
#### System

HyperHDR Server: 
- Build:           (HEAD detached at dec81c0) (Awawa-2a2ed8d/dec81c0-1631541363)
- Build time:      Sep 15 2021 15:59:42
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      macOS (AVF)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   macOS 12.3
- Architecture:   x86_64
- Kernel:         darwin (21.4.0 (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (iPad; CPU OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1

**Comment by awawa-dev** [comment]
no logs, please stop spamming across multiple repos
