### ISSUE TITLE
System Screen Capture glitches

### ISSUE THREAD

**Issue by grigosback** [awawa-dev/HyperHDR#275]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
[Debug log](https://pastebin.com/U0mNuKhi)
[Config file](https://pastebin.com/a3Tsa3rt)

#### Steps to reproduce
1. Go to remote control
2. Enable System Screen Capture
3. Check Live Video in the LED Visualization window

#### What is expected?
It should show the current screen image without gif

#### What is actually happening?
The image looks distorted or glitchy like in the attached picture. This also affects to the LEDs ilumination.
![glitches](https://user-images.githubusercontent.com/33532159/169155584-81ba4157-4e9d-4d41-b70f-ec5c095b1aa0.gif)

#### System
```
HyperHDR Server: 
- Build:           (HEAD detached at d7e3117) (Awawa-bba94d0/d7e3117-1651692977)
- Build time:      May  4 2022 19:47:22
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0beta2
- UI Lang:         auto (BrowserLang: es-419)
- UI Access:       expert
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 11 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.22000 (WS: 64))
- Qt Version:     6.2.4
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36 
```

**Comment by awawa-dev** [comment]
I restored you configuration and test it: works fine.
Since your path is clear but since I can't reproduce the problem I can' fix it. Maybe it's a matter of your graphic card drivers (tested on GTX1060) or Windows 11 (the screen grabber was designed for DX11, the compatibility should be sustained, I can guarantee it for MS).

**Comment by grigosback** [comment]
> I restored you configuration and test it: works fine. Your path is clear but since I can't reproduce the problem I can' fix it. Maybe it's a matter of your graphic card drivers (tested on GTX1060) or Windows 11 (the screen grabber was designed for DX11, the compatibility should be sustained, I can't guarantee it for MS).

In my case I'm using a RTX2060 connected to an Alienware 17 R3 laptop using an Alienware Graphics Amplifier, so maybe the problem is with my particular setup. What's strange to me is that using the [Hyperion Screen Capture](https://sabaatworld.github.io/HyperionScreenCap/) software and sending the image to the HyperHDR server with Flatbuffers works, but I think this is more CPU consuming, that's why I wanted to make the native screen capture works. By the way, I have the same problem using v17 and Hyperion.

**Comment by grigosback** [comment]
And finally, the image glitches only when it is static, if something is moving it works fine

**Comment by grigosback** [comment]
Is it possible to change this priority?
```2022-05-18T16:42:00.536Z [DX11_SYSTEM:\\.\DISPLAY4|N] Found and loaded LUT: 'C:/Program Files/HyperHDR/bin/lut_lin_tables.3d'
2022-05-18T16:42:00.536Z [DX11_SYSTEM:\\.\DISPLAY4|N] Device initialized
2022-05-18T16:42:00.536Z [DX11_SYSTEM:\\.\DISPLAY4|N] Started
2022-05-18T16:42:00.582Z [MUXER0] Priority 200 is now active
2022-05-18T16:42:00.582Z [MUXER0] Set visible priority to 200
2022-05-18T16:42:00.583Z [IMAGETOLED0] Total index number is: 29329 (memory: 29329). User sparse processing is: disabled, image size: 573 x 240, area number: 110
2022-05-18T16:42:00.583Z [HYPERHDR0] New priority[200], previous [255]```

**Comment by awawa-dev** [comment]
> And finally, the image glitches only when it is static, if something is moving it works fine

OK, I know what's probably happens.

**Comment by awawa-dev** [comment]
The problem should be fixed now.
You can find the installer in the latest github action after the build is finished (currently: https://github.com/awawa-dev/HyperHDR/actions/runs/2393373150 )
Let me know if it solved your problem.
You need to check that option:
![obraz](https://user-images.githubusercontent.com/69086569/170588040-7191eccb-1a4d-4514-8536-e688dfc8d3f6.png)

**Comment by grigosback** [comment]
It worked! Thank you so much!
