### ISSUE TITLE
Debian 10 Buster ARMV8 Support

### ISSUE THREAD

**Issue by pman07** [awawa-dev/HyperHDR#28]
#### What problem does this feature solve?
I have a Raspberry Pi 4 running Debian 10 Buster I'd like to install HyperHDR on, but I'm having issues after compiling.

When trying to run Make, the process hangs and will eventually crash or I have to interrupt. I think my RPi4 doesn't have enough memory even after freeing up as much as possible. Is there any way to get this released for armV8?

**Comment by awawa-dev** [comment]
try "make -j 1" instead of "make -j $(nproc)"
if it works you can try to increase it to 2 or 3

**Comment by pman07** [comment]
Thanks for the quick response, "make -j 1" worked. I had tried 2 with no luck.
