### ISSUE TITLE
I don't see v 18.0.0.0 beta3

### ISSUE THREAD

**Issue by pjmpessers** [awawa-dev/HyperHDR#283]
Hello.

I'm fan of the HyperHDR and i'm using it on my rpi4 bullseye 64bits. HyperHDR showed that there was a update to V18.0.0.0Beta2, but it is not shown for beta3?

Is this a fault in my system or is the update not thru yet?

**Comment by awawa-dev** [comment]
Hi Pieter
You were probably already using version 17 (or early version 18beta1) when you received the news about version 18.0.0.0Beta2.
Later in version 18, the notification system was slightly changed when semver was removed and new github alfa/beta versions no longer triggers a notification message: only stable ones. I can modify it a bit and for example: alpha / beta versions will still inform about newer alpha / beta versions. Nevertheless V18 beta3 is probably the last beta for v18: currently I don't plan any new major feature for HyperHDR v18, only bug fixing. So the next release will trigger the update message anyway.

**Comment by pjmpessers** [comment]
Thank you. I found a easy fix for me. It was easier then expected. Just downloaded the assets. Thanks for hyperHDR. Love it.
