### ISSUE TITLE
Possibility to ignore subtitles

### ISSUE THREAD

**Issue by alexkramer98** [awawa-dev/HyperHDR#293]
#### What problem does this feature solve?
When watching TV or movies with subtitles, they are parsed and displayed by HyperHDR as well, resulting in a white glow underneath them.

#### What does the proposed API look like?
No idea.

#### How should this be implemented in your opinion?
Add an option, "subtitle detection". Since subtitles are usually white with black borders, I believe this should be possible. However, I wouldn't have a clue how resource intensive or accurate this would be.

#### Are you willing to work on this yourself?
I unfortunately don't have the necessary skills for the language HyperHDR is written in.

**Comment by jkp1304** [comment]
I dont know if this is possible, but it would be really nice to have!  I had to remove my bottom light strip because of this. So would be really cool to get this implementet if possible, so i can get 4 side ambilight back :)

**Comment by awawa-dev** [comment]
I've got 4 side LED strip, using subtitles all the time and never experience the problem. It's not important but it shows that it can be implemented differently: my subtitles are yellow on the dark semitransparent brown overlay. They are always positioned some space above the last video line so they doesn't affect the LED strips. The black borders are always removed by the video player.

**Comment by alexkramer98** [comment]
This would indeed work for media player supporting this option. 

However, when watching television, the subtitles are baked in to the program, so there is no way to place them underneath the video. 
The only way to avoid this, I think, would be to set the horizontal depth as low as possible, since the subtitles are usually placed at a small distance above above the bottom of the screen. 

Unfortunately, this setting changes the horizontal depth for the top of the screen too.

**Comment by awawa-dev** [comment]
So it's a very specific case for black border detection in HyperHDR to trim the frame. If some part of subtitles are still left on the solid black background the information about the movie content are already lost anyway and cannot be restored (and even if would be possible the LED wouldn't match TV with such visible subtitles).

**Comment by alexkramer98** [comment]
That's true. I think it would be quite hard, if not quite impossible to implement. Of course you could "guess" the color behind the subtitles, but I'd figure it would be too resource intensive for e.g. a Raspberry Pi to handle.

**Comment by awawa-dev** [comment]
A workaround for the case with black frames and lettering could be to extend the height (and possibly a little width to overlap them a little) of the individual LEDs areas on the bottom edge where the subtitles may appear. This is possible by manually editing the LED configuration in the HyperHDR. This will mix & blur the "resolution" of the LED in this section and introduce some content from the middle/down part of the video that is not affected by the subtitles.

**Comment by alexkramer98** [comment]
That could solve the problem for when black bars are around the content. But usually the issue is with full screen content, as illustrated in this picture. I don't believe this can be fixed with the workaround you provided above, could it?

![IMG_20220707_214726](https://user-images.githubusercontent.com/28563299/177860128-d1dc3955-cd86-4560-9ed8-8cf53b641d10.jpg)

**Comment by awawa-dev** [comment]
No, when you enable black border detection in HyperHDR both cases are similar. In this you have subtitles just a little bit higher, but blending/averaging effect for the bottom line should be similar.

**Comment by alexkramer98** [comment]
Actually, setting the horizontal LED depth to 1% does seem to mitigate the issue. I will see if this causes any negative side effects.

Thanks for your help!

**Comment by awawa-dev** [comment]
You may need also Overlap increase a bit. If it work then copy first (before modification) configuration to notepad from here:
![obraz](https://user-images.githubusercontent.com/69086569/177863052-911d13ae-74c6-4b85-b3fd-b2a6ae4fa241.png)
You may need to have advanced user settings level enabled to have it accessible.
Then change horizontal LED depth and optional Overlap and copy new configuration to second notepad.
Then you can copy/paste the bottom line section from the second to first notepad. And finally to HyperHDR.
It's faster than modifying single bottom LED's by a hand.
