### ISSUE TITLE
Allow control of smoothing duration with JSON API

### ISSUE THREAD

**Issue by garrettbeachy** [awawa-dev/HyperHDR#295]
#### What problem does this feature solve?
Different types of media look best with different smoothing durations. Action movies look good with short or no smoothing, and comedies or vlogs look best with longer smoothing times. This would allow for the duration to be updated based on some external logic.
#### What does the proposed API look like?
Accessible outside of the HyperHDR interface through the JSON API.
#### How should this be implemented in your opinion?
It could be implemented in the same way as other API endpoints.
#### Are you willing to work on this yourself?
I do not have the required skills to work on this.

**Comment by pimw1** [comment]
+1 . It has been suggested by me the discussion session too: https://github.com/awawa-dev/HyperHDR/discussions/247
This would be really handy.

**Comment by awawa-dev** [comment]
Implemented https://github.com/awawa-dev/HyperHDR/pull/352
