### ISSUE TITLE
Platform capture 

### ISSUE THREAD

**Issue by BUGBEAR7** [awawa-dev/HyperHDR#30]
Hi, 
Is it possible to enable platform capture for windows setup ?

currently using Rpi3 and that is getting data over flatbuffers from a windows HTPC running Hyperion Screen Capture software. Now instead of using 2 devices what I am planning is to install HyperHDR in my PC and then screen capture features (if that is possible), Hyperion have screen capture feature so I am wondering if that be done in HyperHDR as well.

**Comment by awawa-dev** [comment]
No, there is no screen captures in HyperHDR: they don't work well with video acceleration/DRM and have various side effects so I don't plan them.

**Comment by awawa-dev** [comment]
Closed as non an issue.
