### ISSUE TITLE
Flatbuffer Graber Not working on 18.0 Beta3

### ISSUE THREAD

**Issue by discoluc** [awawa-dev/HyperHDR#300]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
https://pastebin.com/ZPAztNw8

#### Steps to reproduce
Using Piccap and HyperHDR 18 Beta3. 
#### What is expected?
Seeing a flatbuffer source in the remote section. Like it is with 17.0
#### What is actually happening?
No source is visible. 
#### System

System info

HyperHDR Server: 
- Build:           (HEAD detached at 8d314bc) (Awawa-5b8ed09/8d314bc-1654356765)
- Build time:      Jun  4 2022 15:51:17
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0beta3
- UI Lang:         en (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   c03111
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.32-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (iPh

**Comment by awawa-dev** [comment]
First of all, webos version & configurations are not supported and maintained by me, but for sure I'll fix potential bugs that I can reproduce on the HyperHDR to HyperHDR flatbuffer communication. Secondly flatbuffers for sure works in v18beta3: tested by me (HyperHDR to HyperHDR) and many people using piccap (please check webos discord). In your logs I can't see any attempt to establish flatbuffer connection so I would look for the problem outside (network/firewall/piccap configuration). BTW your network is available about 10 seconds after starting HyperHDR.

**Comment by discoluc** [comment]
I am not using the WebOS HyperHDR. It is running on my raspberry pi. Everything is running find with 17.0 as soon as I installiert 18.0 it is Not working any more. Without any settings changed.

**Comment by awawa-dev** [comment]
I know but your are using external flatbuffer server which I don't support.  Only HyperHDR to HyperHDR flatbuffer configuration are officially supported. But it's working even with piccap, I can assure you. I can only hope that your piccap version can communicate on the non-standard 19445 port, but if it worked before....

**Comment by discoluc** [comment]
Waiting for the official Version. Doing a clean install then:
