### ISSUE TITLE
WLED live property

### ISSUE THREAD

**Issue by mctigger** [awawa-dev/HyperHDR#308]
Hi,
I have a question and depending on the answer it is a bug report :)

I realized that when I shutdown my HyperHDR instance (by just turning off power to the raspberry) my WLED instance will stay in the last frame instead of resetting to the default color.

I think it is related to this issue: 
https://github.com/Aircoookie/WLED/issues/2653

Is HyperHDR also making use of this `live` property? Or am I doing something wrong with my setup?

**Comment by awawa-dev** [comment]
Yes, ```live``` property is supported since v17 https://github.com/awawa-dev/HyperHDR/issues/90#issuecomment-902179625 What do you mean by turning off the power? Suddenly shutdown don't give a chance to send that command. Or maybe HyperHDR is closed when the network is already down.

**Comment by awawa-dev** [comment]
So since it is supported closing now as non-issue. You can continue the topis in the discussion if you want.
