### ISSUE TITLE
Just question: Update to V18?

### ISSUE THREAD

**Issue by seppelicous** [awawa-dev/HyperHDR#324]
Congratulations to V18! I reinstalled beta 3 and the the Colors are now perfect - thank you very much!

Just a short question, is there any option to automatically update vom 18b3 to final V18? The Wiki only mentions a complete reinstall.

Thank you very much!

**Comment by awawa-dev** [comment]
Hi
Currently there is no automatic update mechanism (for example using ```apt```) since HyperHDR releases are available on the github, not on the repo server. Or you want to just avoid SD card image re-flashing? It's possible if you have flashed v18beta3 before, but not for old v17 SD image (Raspbian migrated from buster to bullseye in the meantime).

**Comment by S0und** [comment]
Absolute offtopic, but i don't want to open an issue for this:

For the #grabber_calibration process i would add a 7th bullet point:

* The TV has to be the main (primary) display

I just pulled over the calibration window, and when i tried to run it complained about the window not being in full screen (F11) even tho it was full screen. Setting the TV as a primary display solved the issue, and the calibration started and run successfully.

**Comment by S0und** [comment]
Well, when my TV is also plugged into my PC, i have 4 active displays (3 monitors + the TV). Although +1 or +3 shouldn't matter, but i had trouble starting the calibration. The browser was Firefox btw.

**Comment by seppelicous** [comment]
Similar question from my side:
I only use apple tv with DV activated. Is it possible to use this as a source for the automatic test and start the calibration on a different device?

**Comment by seppelicous** [comment]
> Hi
> Currently there is no automatic update mechanism (for example using `apt`) since HyperHDR releases are available on the github, not on the repo server. Or you want to just avoid SD card image re-flashing? It's possible if you have flashed v18beta3 before, but not for old v17 SD image (Raspbian migrated from buster to bullseye in the meantime).

Thank you! Then I just delete the old installation and install the newer version as described.

**Comment by awawa-dev** [comment]
> Similar question from my side: I only use apple tv with DV activated. Is it possible to use this as a source for the automatic test and start the calibration on a different device?

If you can run the web-browser on Apple TV with HyperHDR wizard page in full screen then you may try it. Didn't test it myself.
