### ISSUE TITLE
Video capture fails after upgrading from v17 to v18

### ISSUE THREAD

**Issue by sorcererlc** [awawa-dev/HyperHDR#326]
#### Steps to reproduce
- Have a fully functional instance of HyperHDR v17
- Install v18 on top of v17
- Rebuild configuration (when first installed v18 all configuration from v17 was lost, subsequent upgrades and downgrades preserved configuration)

#### What is expected?
Video capture should and LEDs should work.

#### What is actually happening?
Video capture fails with error `Unsupported MJPEG/YUV format. Please contact HyperHDR developers! (info: UNSUPPORTED YUV DECODER: 2)`. Full logs here: [https://pastebin.com/Gy0H48ii](https://pastebin.com/Gy0H48ii)

In case it helps, the capture card used is a 4K ZasLuke Game Capture Card - https://smile.amazon.de/gp/product/B08D3PHT58

#### System
HyperHDR Server: 
- Build:           (HEAD detached at 1c31205) (Awawa-e327d52/1c31205-1661084784)
- Build time:      Aug 21 2022 14:03:34
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         18.0.0.0
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 3 Model B Rev 1.2
- CPU Revision:   a02082
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.32-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.105 Safari/537.36

**Comment by awawa-dev** [comment]
Currently your grabber is not supported in HyperHDR from v18. It's explained here: https://github.com/awawa-dev/HyperHDR/discussions/323

**Comment by sorcererlc** [comment]
My mistake, I searched for various parts of the error message but did not notice that other issue.

Disabling HDR to SDR tone mapping does allow HyperHDR to start video capture but obviously the colors are all wrong.
I will monitor https://github.com/awawa-dev/HyperHDR/discussions/323 for a solution and revert to v17 until then.

Thanks!

**Comment by awawa-dev** [comment]
Hi
Updated: https://github.com/awawa-dev/HyperHDR/discussions/323

**Comment by sorcererlc** [comment]
Hi

It seems to work with the test build. I left a reply on https://github.com/awawa-dev/HyperHDR/discussions/323 to we can keep the discussion in a single place.

I'll stay with this test build until you merge the change into master.

Thanks!
