### ISSUE TITLE
GLIBC not found on Debian Buster with Asus Tinker Board

### ISSUE THREAD

**Issue by dapostol73** [awawa-dev/HyperHDR#338]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
Not sure if this is a bug or something.  Trying to get HyperHDR-18.0.0.0-Linux-armv7l.deb running on Asus Tinker Board and getting and issue where the Service won't start, running the following command "/usr/bin/hyperhdr -d" spits out and issue with GLIBC

/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/hyperhdr)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/bin/hyperhdr: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/bin/hyperhdr: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Widgets.so.5)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Gui.so.5)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/bin/hyperhdr: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/bin/hyperhdr: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/share/hyperhdr/bin/../lib/libQt5Core.so.5)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libasound.so.2)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libpng16.so.16)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libicui18n.so.67)
/usr/bin/hyperhdr: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hyperhdr/bin/../lib/libicuuc.so.67)

#### Steps to reproduce
Install HyperHDR on Asus Tinker Board using the latest OS from Asus (Debian 10 V3.0.11), then try and start the service and run command /usr/bin/hyperhdr -d

#### What is expected?
The Service to start

#### What is actually happening?
The Service does not start

#### System

Can't do this as the service never starts.

[syslog.txt](https://github.com/awawa-dev/HyperHDR/files/9502080/syslog.txt)

**Comment by awawa-dev** [comment]
Hi
A similar situation to https://github.com/awawa-dev/HyperHDR/discussions/262 . If you are not able to upgrade Debian Buster to newer version then you can always compile HyperHDR deb installer on your device (manual is in the wiki) or using ARM Debian 11 docker.

**Comment by dapostol73** [comment]
Thanks for the info, going to try and run with the lasted DietPi image for Asus TinkerBoard

**Comment by dapostol73** [comment]
I tried DietPi too and got farther, but now I am getting SIGILL error, instead of opening another issue, figure it was better to start a discussion. 

https://github.com/awawa-dev/HyperHDR/discussions/340
