### ISSUE TITLE
v16 to v18

### ISSUE THREAD

**Issue by markmghali** [awawa-dev/HyperHDR#342]
#### Steps to reproduce
upgraded from v16 to v18 on a Raspbery Pi 2. I took a backup of my settings but cannot import due to incompatibility. anyway to use my json backup to retrieve my settings?

**Comment by awawa-dev** [comment]
In case of problems I suggest you to upgrade to v17 first. Then to v18. If you have JSON backup from v16, then you must install HyperHDR v16 to restore it. HyperHDR v17 and above is using different backup format that includes all instances (previously one one instance was backup).

**Comment by markmghali** [comment]
ok, I think I already have v18 reconfigured. Thank you again for the amazing work
