### ISSUE TITLE
LG WebOS HyperHDR

### ISSUE THREAD

**Issue by satgit62** [awawa-dev/HyperHDR#350]
Could one, in a future version of HyperHDR for LG WebOS (PicCap), also determine the brightness of the “WLED” LEDs when starting from 0 to 255?

**Comment by awawa-dev** [comment]
Hi
You should probably submit this proposal to a project that provides compilation for WebOS as I don't know if it will be noticed here. This system is not officially supported by HyperHDR Regardless of the system in which it is supposed to run, the WLED driver extension in the HyperHDR itself should at least have a functional path described which takes into account the WLED API. However, it has to wait until WLED deals with its own stability issues, at least as far as the part where HyperHDR and HyperSerialWLED are concerned.

**Comment by awawa-dev** [comment]
I prepared a PR which should support the maximum brightness setting and additionally it can save and restore WLED state. If you manage to test it, please provide feedback to see if it works properly on your system.
Pull request: https://github.com/awawa-dev/HyperHDR/pull/353

**Comment by satgit62** [comment]
Thank you very much, I will test and report if everything works.
