### ISSUE TITLE
Error compile OS X

### ISSUE THREAD

**Issue by appleimperio** [awawa-dev/HyperHDR#36]
## Bug report, debug log and your config file (optional but could be very helpful)
 error: 
      'toIndex' is a private member of 'ImageData'
                return _d_ptr->toIndex(x, y);

#### Steps to reproduce

Im using the same instructions to compile Hyperionng downloading all dependencies with brew.

#### What is expected?
If I compile hyperiong it works when I try to compile HyperionHDR failed

#### What is actually happening?
 error: 
      'toIndex' is a private member of 'ImageData'
                return _d_ptr->toIndex(x, y);

**Comment by awawa-dev** [comment]
Sorry, OSX is not supported. And there is no USB grabber support for that system anyway (in HyperHDR or Hyperion Ng).
As I don't have any Apple's Mac for developing I'm unable to provide that feature.

**Comment by appleimperio** [comment]
Ohh ok thank you

**Comment by awawa-dev** [comment]
Managed to fix it and to run HyperHDR on MacOS, but still no support for USB grabber at this moment.
