### ISSUE TITLE
Service doesn't start

### ISSUE THREAD

**Issue by CzechSebastian** [awawa-dev/HyperHDR#362]
### Discussed in https://github.com/awawa-dev/HyperHDR/discussions/361

<div type='discussions-op-text'>

<sup>Originally posted by **CzechSebastian** September 26, 2022</sup>
Hi,

After a fresh installation of hyperhdr , the hyperhdr@pi.service doesn't start.
I have this error when I `sudo systemctl status  hyperhdr@pi.service`

```
● hyperhdr@pi.service - HyperHdr ambient light systemd service  for user pi
     Loaded: loaded (/etc/systemd/system/hyperhdr@.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-09-26 21:20:28 EDT; 1s ago
    Process: 9842 ExecStart=/usr/bin/hyperhdr (code=exited, status=127)
   Main PID: 9842 (code=exited, status=127)

Sep 26 21:20:31 raspberrypi systemd[1]: hyperhdr@pi.service: Scheduled restart job, restart counter is at 24.
Sep 26 21:20:31 raspberrypi systemd[1]: Stopped HyperHdr ambient light systemd service  for user pi.
Sep 26 21:20:31 raspberrypi systemd[1]: Started HyperHdr ambient light systemd service  for user pi.
Sep 26 21:20:31 raspberrypi hyperhdr[9850]: /usr/bin/hyperhdr: error while loading shared libraries: libz.so.1: cannot open share>
Sep 26 21:20:31 raspberrypi systemd[1]: hyperhdr@pi.service: Main process exited, code=exited, status=127/n/a
Sep 26 21:20:31 raspberrypi systemd[1]: hyperhdr@pi.service: Failed with result 'exit-code'.
```

How can I do ? 

Thanks</div>

**Comment by awawa-dev** [comment]
Hi
Run HyperHDR from the command line (it's in the guideline in Wiki) and provide full error message. What's your OS and its version&architecture/when installed/downloaded from?

**Comment by CzechSebastian** [comment]
Hi,

I run 
HyperHDR-17.0.0.0-Linux-armv7l.deb
  On a raspeberry pi 4 with 8gb of ram an Debian Bullseyes
 <https://github.com/awawa-dev/HyperHDR/releases/download/v17.0.0.0/HyperHDR-17.0.0.0-Linux-armv7l.deb>
When I run HuperHdr on command line I have 

hyperhdr: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

I download it from official repo  with a wget and apt install.

This is a screenshot of the installation process

**Comment by CzechSebastian** [comment]
The screenshot is the 18 version version but I tried both and same result,

**Comment by awawa-dev** [comment]
And that Debian Bullseye for arm7 comes from...? Probably you need to install package providing libz.so.1 in that case.

**Comment by CzechSebastian** [comment]
The debian package come from the Raspberry pi image installer How can I do that for libz.so.1?Le 27 sept. 2022 à 06:58, Awawa ***@***.***> a écrit :﻿
And that Debian Bullseye for arm7 comes from...? Probably you need to install package providing libz.so.1 in that case.

**Comment by awawa-dev** [comment]
I'm not sure, maybe ```zlib1g``` . For arm7v officially supported is only Raspberry Pi OS, anyway for Rpi4 aarch64 version & 64bit OS  is strongly recommended for HyperHDR due to much higher performance.

**Comment by CzechSebastian** [comment]
I'll test aarch64 version later this day.Thanks Le 27 sept. 2022 à 07:04, Awawa ***@***.***> a écrit :﻿
I'm not sure, maybe zlib1g . For arm7v officially supported is only Raspberry Pi OS, anyway for Rpi4 aarch64 version & 64bit OS  is strongly recommended for HyperHDR due to much higher performance.

**Comment by CzechSebastian** [comment]
If I want to use on rpi 4 with 4gb of ram, which deb can I use?Le 27 sept. 2022 à 07:05, Sebastian CZECH ***@***.***> a écrit :﻿I'll test aarch64 version later this day.Thanks Le 27 sept. 2022 à 07:04, Awawa ***@***.***> a écrit :﻿
I'm not sure, maybe zlib1g . For arm7v officially supported is only Raspberry Pi OS, anyway for Rpi4 aarch64 version & 64bit OS  is strongly recommended for HyperHDR due to much higher performance.

**Comment by awawa-dev** [comment]
RPi memory size doesn't affect the installer choice. The rest is described in the wiki/installation section.

**Comment by CzechSebastian** [comment]
If I use arm7l on 64bits that's why it doesn't work?Le 27 sept. 2022 à 11:10, Awawa ***@***.***> a écrit :﻿
RPi memory size doesn't affect the installer choice. The rest is described in the wiki/installation section.

**Comment by awawa-dev** [comment]
Are you sure you are using 64-bit ARM OS? Type ```dpkg --print-architecture``` and check it for ```arm64``` occurrence.
Yes, using arm7l may be disabled by 64-bit OS configuration or problems with depended libraries may happen.

**Comment by CzechSebastian** [comment]
Its been the package version, with the aarch64 its running good !
Thanks for your help !

**Comment by awawa-dev** [comment]
Great! So I'm closing the issues now.
