### ISSUE TITLE
DRM feature request

### ISSUE THREAD

**Issue by konrul-r10** [awawa-dev/HyperHDR#377]
#### What problem does this feature solve?

Kodi v19 Matrix installed on the RPi4 Bullseye Raspbian OS can't run ambient light with HyperHDR. DRM Flatbuffers Server can solve the issue. Moreover, people can use ambient light without any capture device.

#### What does the proposed API look like?
The mentioned thing can be found in here: https://github.com/rudihorn/drm-vc4-grabber
#### How should this be implemented in your opinion?
This should be work in hyperHDR without any programming knowledge. 
#### Are you willing to work on this yourself?
I can be a tester, I am not an expert on such programming area.

**Comment by awawa-dev** [comment]
Currently the main approach for DRM is using the Pipewire to access the video stream including the hardware acceleration video format decoding if necessary. You can test it here: https://github.com/awawa-dev/HyperHDR/pull/556 although I didn't test it on Rpi. Direct raw DRM buffer access is heavily platform depended and I don't plan it unless some need API (that could decode the DRM stream if necessary) appears. Then the PR can be opened again.
