### ISSUE TITLE
Blacklist LEDs

### ISSUE THREAD

**Issue by flos06** [awawa-dev/HyperHDR#418]
#### What problem does this feature solve?

The ability to blacklist certain LEDs. 
In my case the led strip starts at the middle bottom of the TV. I want to completely ignore (blacklist) the first leds as my tv is on a stand and I don't want the bottom to light up. The leds are actually there so I don't want gaps. I believe hyperion ng has a blacklist feature implemented?
I've tried manually disabling leds by putting these values at 0 for the leds i want to ignore:
  {
    "group": 0,
    "hmax": 0,
    "hmin": 0,
    "vmax": 0,
    "vmin": 0
  },

However the Leds still light up.

#### How should this be implemented in your opinion?

Preferably with a UI option, however if it can be done manually I would like some help on how to set it up.

#### Are you willing to work on this yourself?
I would if I knew how.

**Comment by flos06** [comment]
Just as I typed it I found on the hyperion forum that {
"group": 0,
"hmax": 0,
"hmin": 0,
"vmax": 0,
"vmin": 0
},
doesn't work if using a remote control. I'm using protobuffers. Any other possibilities or is this simply not feasible?

**Comment by awawa-dev** [comment]
Hi
I think you may want to try new context menu from the LED strip geometry designer (v19 beta1). Description: https://github.com/awawa-dev/HyperHDR/pull/379  
```3 Disable/enable selected LED. The LED is still transmitted but its color is set to black.``` You don't need to manually edit JSON configuration file, just mouse click on the LED you want to disable.

**Comment by flos06** [comment]
So this works however if I use a backlight threshold in image processing the disabled lights still light up.
Any way to have those be disabled when using a backlight threshold?
Thanks for your help :)

**Comment by flos06** [comment]
If I enable backlight threshold I get this error message at the generated LED config:

[0] | should NOT have additional property: disabled
-- | --
  | [1] | should NOT have additional property: disabled
  | [2] | should NOT have additional property: disabled
  | (64 more errors...)

**Comment by awawa-dev** [comment]
> If I enable backlight threshold I get this error message at the generated LED config:
[0] | should NOT have additional property: disabled
-- | --
  | [1]
  | [2]
  | (64 more errors...)

Could you provide that communicate in more readable form if the problem still occurs? 

I will take a look in the post-processing side effect. I haven't take it into account before, but it's quite possible that post-processing overrides the black LEDs. Need to be fixed.

**Comment by flos06** [comment]
I've attached a screenshot. However it appears that the led config ui doesn't like disabled leds at all. It doesn't matter if backlight is on or not it spits out the error anyways. 
"but it's quite possible that post-processing overrides the black LEDs." This would be my guess as to the issue.
![leds](https://user-images.githubusercontent.com/30049768/202719397-f4f9defe-11a2-4ea0-bd66-fbb84a9b7c68.png)

**Comment by awawa-dev** [comment]
Thanks. I'll keep you updated. These things need to be fixed before v19 stable release.

**Comment by awawa-dev** [comment]
I think I fixed it. The installer will be ready to download when finished:
https://github.com/awawa-dev/HyperHDR/actions/runs/3499994403

**Comment by flos06** [comment]
Thanks for the quick update.
I can confirm that the errors no longer appear and that the LEDs stay deactivated with backlight threshold on.
However I have one more issue of which I am unsure if its doable.
For my own media I use hyperion as ambilight. However as we all know this does not work with DRM. So if I watch for example Netflix I have home assistant send the color white to hyperion which gives me some nice bias lighting instead. The disabled LEDs still light up using this. 
Do you have any ideas on how to make
![remote control](https://user-images.githubusercontent.com/30049768/202813966-ab96d4fa-c057-423d-8b8b-ce60ff530f1a.png)
 the disabled leds stay disabled?
![home assistance leds](https://user-images.githubusercontent.com/30049768/202813843-054d5942-ff13-4919-9de6-4415e624f138.png)

**Comment by flos06** [comment]
The same happens with colors/effects 
![colors](https://user-images.githubusercontent.com/30049768/202814294-2d773613-0302-4536-a922-f2c262940ab5.png)

**Comment by awawa-dev** [comment]
Yes, colors using different path than images (usb grabber/flatbuffers/protobuffers).
Try this:
https://github.com/awawa-dev/HyperHDR/actions/runs/3501002337

Just one small thing: colors are not live updated so when you are designing LED strip geometry and disable/enable some LEDs you need to apply color again to have it visible in the preview/LED output. It's only design time limitation.

**Comment by awawa-dev** [comment]
I've found another "back-door" that allowed colors for disabled leds: effects that use direct LED rendering like "Breath". So decided to fix it in another way, in a place where all these paths come together. Hope it's final solution.
https://github.com/awawa-dev/HyperHDR/actions/runs/3503207669

**Comment by flos06** [comment]
Thanks I can confirm this solved everything :)
