### ISSUE TITLE
Screen capture is not restored after re-enabling the instance

### ISSUE THREAD

**Issue by moran-x** [awawa-dev/HyperHDR#431]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

[Log](https://pastebin.com/gCZ1ss31)
[Config](https://pastebin.com/KHwTdRrN)
#### Steps to reproduce
1. Run RP4, Kodi - Everything works great (light, capture), for a long time.
2. Shutting down the instance as unnecessary (in the web interface).
3. After about 6-8 hours, the instance is turned on (in the web interface).

#### What is expected?
Resuming an Instance

#### What is actually happening?
The backlight starts, but goes into rainbow mode, there is no screen capture, but any effect can be enabled in the web interface and the effect will work.
Restarting the HyperHDR service does nothing. Only a full system restart makes the screen capture work.

#### System

HyperHDR Server: 
- Build:           (HEAD detached at d5564ff) (Awawa-eed8ea2/d5564ff-1667760501)
- Build time:      Nov  6 2022 19:55:14
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         19.0.0.0beta1
- UI Lang:         auto (BrowserLang: ru-RU)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 4 Model B Rev 1.4
- CPU Revision:   c03114
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.76-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**Comment by awawa-dev** [comment]
Hi
So the problem appears after few hours and you attached logs that last few second not related to the problem? Nevermind because:

> Restarting the HyperHDR service does nothing. Only a full system restart makes the screen capture work.

That's a really strong indicator that something's wrong with the system or the capturing device. From the provided details I can only recommend you to check the system log first when that happens. Maybe system powered down unused device.
