### ISSUE TITLE
live LUT calibration

### ISSUE THREAD

**Issue by pho084** [awawa-dev/HyperHDR#443]
hi awawa

i have no idea if something like this is possible/conceivable, but here is an idea that would help me a lot:

problem: i have my LUT calibrated for content/source A but when i switch to different source or even different HDR content on the same source, the output in hyperHDR is too bright/dark/saturated/etc.

a quick and easy way to adjust this on the fly would thus be a godsent. otherwise i always have to tinker w the LUT, compile it, apply it, etc

feedback appreciated. thanks!

**Comment by awawa-dev** [comment]
and the video source for HyperHDR is?

**Comment by pho084** [comment]
Windows mostly.
for instance hdr implementation in games differs vastly

**Comment by awawa-dev** [comment]
Software capturing? Did you calibrate the LUT? If you want to have a constant result then maybe choose USB grabber or use flatbuffers/protobuffers as source (there is a JSON API method to switch LUT table on fly).

**Comment by awawa-dev** [comment]
What was the result for the calibration from the logs?

**Comment by pho084** [comment]
> Software capturing? Did you calibrate the LUT? If you want to have a constant result then maybe choose USB grabber or use flatbuffers/protobuffers as source (there is a JSON API method to switch LUT table on fly).

Its via Hyperion-webos from LG tv

**Comment by pho084** [comment]
yup but that doesn't really solve my problem bc i would have to create LUTs for every other game and then set up a myriad of automations for each

**Comment by awawa-dev** [comment]
Yes but frankly what do you expected? Multiple custom LUTs allows you to best possible solution to correct the colors and also the live preview corrected, if you want just brightness/saturation correction for LEDs then you also have already function in the JSON API to adjust them. In both cases you need to have prepared profiles to switch them.

**Comment by chcore** [comment]
@pho084 This might be slightly off topic, but can you please provide more information about how you are calibrating colours? I too have a hyperion-webos grabber running, and am finding it difficult to get a generally accurate configuration.

I am really just doing a lot of trial and error with colour/gamma/brightness values in HyperHDR's image processing page, but find it hard to get good, consistent results. When I manage to get a few colours looking good, I notice other colours now look worse. So I adjust slightly to fix them, only to find more colours that were previously good are now looking worse. This tends to go on until I get frustrated and give up.

**Comment by pho084** [comment]
heh' that's exactly what i have been doing so far .. which is tedious and why i was asking for this live calibration feature

what's worse is that i forgot to write down my current settings which are not bad but not perfect and now i have a LUT i do not know how to improve on bc i lost the parameters

i have tried the auto calibration feature mentioned by @awawa-dev but it just does not produce satisfactory results for webos capture.

when i find the time i will create some LUTs to approximately find out my original settings and let you know.

again a live calibration feature would be the ultimate solution for setting up/fine tuning a LUT and adapting it to different environments (i.e. sources)

**Comment by awawa-dev** [comment]
closing since its not an issue and webos is not officially supported
