### ISSUE TITLE
HDR tone mapping for external grabbers

### ISSUE THREAD

**Issue by ClassicGOD** [awawa-dev/HyperHDR#46]
## Feature request

HDR Tone mapping like for USB grabber but for network sources.

#### What problem does this feature solve?

AFAIK no PC grabbers handle HDR on PC correctly leading to washed out colors in the captured image sent to HyperHDR.  

#### How should this be implemented in your opinion?

If possible by applying HDR Tone mapping already present for USB grabbers to network sources.

**Comment by awawa-dev** [comment]
What network protocol for that connection to external USB grabber? Do you mean HDR tone mapping for input protobuf stream from other instance of application on another PC/machine?

**Comment by ClassicGOD** [comment]
Not a USB grabber but a software one. Right now I'm using Flat Buffers form an PC application.

**Comment by awawa-dev** [comment]
Could you provide more details? What kind of software source is generating that video stream using flatbuffers? If it's a video player then it should be capable to do tone mapping on his own so it's something else?

**Comment by ClassicGOD** [comment]
I'm using Hyperion Screen Capture - https://sabaatworld.github.io/HyperionScreenCap/ It uses DirectX to capture the screen and while you can tone map this image I'm not familiar with DX enough to contribute.

**Comment by awawa-dev** [comment]
Ah, OK. Tone mapping implemented in HyperHDR is meant to work with USB grabbers because they strip and don't apply certain HDR metadata transmitted via HDMI. But it should not be the case with Hyperion Screen Capture as it captures the video content at source (as screen grabber): HDMI is not even touched. Also the video/demo at that projects's homepage shows proper colors I think.

**Comment by ClassicGOD** [comment]
I think the video it not titled correctly as many people report HDR issues on this project. 
The grabber definitely sends a washed out image to Hyperion. The image looks very similar to "before" images on HyperHDR project homepage and while it does not touch HDMI the source of the issue is similar - casting HDR data into SDR without tone mapping. 
I tested multiple grabbers, even ones communicating directly with LED controllers without Hyperion and all of them have this issue in HDR. I started researching the root cause of this and even found potential solution that I even already mentioned on Hyperion Screen Capture Github but that project is much less active. 

So not knowing how HyperHDR tone mapping operates I was hoping it will be simple to implement and decided to ask.

**Comment by awawa-dev** [comment]
DirectX11 software grabber is now implemented in version 17 (beta for testing) with an option for tone mapping so no need to use external software here.
If you have some time, please test it. Reopen the issue if needed.
https://github.com/awawa-dev/HyperHDR/releases/tag/v17.0.0.0beta

**Comment by fightforlife** [comment]
I have a very similar problem with the Kodi addon capturer over network.
HDR content shows very washed out LEDs.
Is this something that can be fixed hyperhdr or the Kodi addon?

**Comment by awawa-dev** [comment]
Yes, there is tone mapping available for flatbuffer/protobuffer stream compatible with HyperHDR

**Comment by fightforlife** [comment]
I think I found it, thanks for the hint!
Do I need to enable both:
- Advanced, Network, Flatbuffer, Tonemapping
- image processing, automatic tone mapping

or is the second one only for USB capure?

**Comment by awawa-dev** [comment]
Advanced, Network, Flatbuffer, Tonemapping should be enough
