### ISSUE TITLE
Black Screen.  Leds are still on

### ISSUE THREAD

**Issue by chris627** [awawa-dev/HyperHDR#48]
When the screen is black from a scene change of a movie or game. The leds are a dim white. How do I get them to turn off when the movie scene or game demands it?

**Comment by awawa-dev** [comment]
Please start a topic in the discussion section (https://github.com/awawa-dev/HyperHDR/discussions) and provide some info about your config. Guessing it's not a pure black screen you may think you see but a very dark gray that the grabber captures or you have minimal brightness set in your configuration.
