### ISSUE TITLE
Disable processing video capture while LEDs are off

### ISSUE THREAD

**Issue by lucasfeijo** [awawa-dev/HyperHDR#490]
## Feature request

Disable processing video capture while LEDs are off

#### What problem does this feature solve?

Unnecessary CPU and power usage while no LED is consuming the processed image.

#### What does the proposed API look like?

It wouldn't require API changes.

#### How should this be implemented in your opinion?

I'm not familiar with the hyperion codebase, but I think there would be modifications to the source selection logic to receive the on/off status of the LEDs and disable all sources if no LED controller reports being on.

#### Are you willing to work on this yourself?

Possibly if someone else gives me some information to get started.

**Comment by awawa-dev** [comment]
Implemented in https://github.com/awawa-dev/HyperHDR/pull/608
