### ISSUE TITLE
candle effect from hyperion.ng

### ISSUE THREAD

**Issue by scr44tch** [awawa-dev/HyperHDR#51]
## Feature request

is it possible to import the candle effect from hyperion.ng?

**Comment by awawa-dev** [comment]
Yep, quite easy to import. Next release.

**Comment by scr44tch** [comment]
sounds great, thx

**Comment by awawa-dev** [comment]
Hi
Candle effect is imported into the new release https://github.com/awawa-dev/HyperHDR/releases/tag/v16.0.0.0 (currently in the beta phase)
