### ISSUE TITLE
Can't use ws281x LED Hardware

### ISSUE THREAD

**Issue by weitheng** [awawa-dev/HyperHDR#52]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
> 2021-03-29T18:03:51.740Z [MAIN] (INFO) Starting HyperHdr - 15.0.0.0, (HEAD detached at caaceec) (Awawa-7d37aa4/caaceec-1614632873), built: Mar  1 2021:22:23:26
> 2021-03-29T18:03:51.742Z [MAIN] (INFO) Set user data path to '/home/pi/.hyperhdr'
> 2021-03-29T18:03:51.770Z [DB] (INFO) Database opened: /home/pi/.hyperhdr/db/hyperhdr.db
> 2021-03-29T18:03:52.284Z [HYPERHDR] (INFO) Sound device is disabled
> 2021-03-29T18:03:52.363Z [SETTINGSMGR] (DEBUG) (SettingsManager.cpp:109:SettingsManager()) Settings database initialized
> 2021-03-29T18:03:52.365Z [BLACKBORDER] (INFO) Set mode to: default
> 2021-03-29T18:03:52.365Z [COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Blackborder detector: enabled
> 2021-03-29T18:03:52.366Z [IMAGETOLED] (DEBUG) (ImageProcessor.cpp:153:setLedMappingType()) set user led mapping to advanced
> 2021-03-29T18:03:52.366Z [IMAGETOLED] (DEBUG) (ImageProcessor.cpp:136:setSparseProcessing()) setSparseProcessing to 0
> 2021-03-29T18:03:52.367Z [RgbTransform] (DEBUG) (RgbTransform.cpp:36:init()) RGB transform classic_config: 0, saturationGain: 1.000000, luminanceGain: 1.000000
> 2021-03-29T18:03:52.368Z [RgbTransform] (DEBUG) (RgbTransform.cpp:36:init()) RGB transform classic_config: 0, saturationGain: 1.000000, luminanceGain: 1.000000
> 2021-03-29T18:03:52.371Z [ChannelAdjust_RED] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:03:52.371Z [ChannelAdjust_BLUE] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:03:52.372Z [ChannelAdjust_GREEN] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:03:52.624Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:1395:setDeviceVideoStandard()) setDeviceVideoStandard restarting v4l2 grabber. Old: '' new: 'auto'
> 2021-03-29T18:03:52.624Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:85:V4L2Grabber()) Init pixel format: 6
> 2021-03-29T18:03:52.624Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:195:setHdrToneMappingEnabled()) setHdrToneMappingMode to: Disabled
> 2021-03-29T18:03:52.624Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:181:setFpsSoftwareDecimation()) setFpsSoftwareDecimation to: 1
> 2021-03-29T18:03:52.625Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:1487:setEncoding()) Force encoding (setEncoding): NO_CHANGE (NO_CHANGE)
> 2021-03-29T18:03:52.625Z [V4L2:AUTO] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
> 2021-03-29T18:03:52.625Z [V4L2:AUTO] (INFO) setQFrameDecimation is now: disabled
> 2021-03-29T18:03:52.625Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:1522:setBrightnessContrastSaturationHue()) setBrightnessContrastSaturationHue nothing changed
> 2021-03-29T18:03:52.625Z [V4L2:AUTO] (INFO) Signal detection is now disabled
> 2021-03-29T18:03:52.626Z [V4L2:AUTO] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
> 2021-03-29T18:03:52.626Z [DAEMON] (DEBUG) (hyperhdr.cpp:457:handleSettingsUpdate()) V4L2 grabber created
> 2021-03-29T18:03:52.626Z [JSONSERVER] (DEBUG) (JsonServer.cpp:28:JsonServer()) Created instance
> 2021-03-29T18:03:52.627Z [JSONSERVER] (INFO) Started on port 19444
> 2021-03-29T18:03:52.374Z [DB] (INFO) Database opened: /home/pi/.hyperhdr/db/hyperhdr.db
> 2021-03-29T18:03:52.394Z [COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Smoothing: enabled
> 2021-03-29T18:03:52.395Z [LEDDEVICE] (INFO) Start LedDevice 'file'.
> 2021-03-29T18:03:52.395Z [SMOOTHING] (DEBUG) (LinearColorSmoothing.cpp:70:handleSettingsUpdate()) Creating smoothing config (0) => direct mode: false, pause: false, settlingTime: 150 ms, interval: 12 ms (83 Hz), updateDelay: 0 ms
> 2021-03-29T18:03:52.395Z [SMOOTHING] (INFO) Selecting smoothing config (0) => direct mode: false, pause: false, settlingTime: 150 ms, interval: 12 ms (83 Hz), updateDelay: 0 ms
> 2021-03-29T18:03:52.395Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:149:init()) deviceConfig: [{"colorOrder":"rgb","currentLedCount":1,"hardwareLedCount":1,"latchTime":0,"output":"/dev/null","rewriteTime":0,"type":"file"}]
> 2021-03-29T18:03:52.395Z [SMOOTHING] (INFO) Selecting smoothing config (0) => direct mode: false, pause: false, settlingTime: 150 ms, interval: 12 ms (83 Hz), updateDelay: 0 ms
> 2021-03-29T18:03:52.395Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:408:setLatchTime()) LatchTime updated to 0ms
> 2021-03-29T18:03:52.395Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:435:setRewriteTime()) RewriteTime updated to 0ms
> 2021-03-29T18:03:52.395Z [LEDDEVICE] (DEBUG) (LedDeviceFile.cpp:59:open()) QIODevice::WriteOnly, /dev/null
> 2021-03-29T18:03:52.397Z [FLATBUFCONN] (INFO) Connecting to HyperHDR: 127.0.0.1:19401
> 2021-03-29T18:03:52.400Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:162:registerInput()) Register new input 'System/V4L' with priority 240 as inactive
> 2021-03-29T18:03:52.400Z [COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) V4L capture device: enabled
> 2021-03-29T18:03:52.640Z [V4L2:AUTO] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
> 2021-03-29T18:03:52.642Z [V4L2:AUTO] (INFO) available V4L2 devices:
> 	/dev/video0	USB Video: USB Video
> 	/dev/video14	bcm2835-isp-capture0
> 	/dev/video15	bcm2835-isp-capture1
> 
> 2021-03-29T18:03:52.642Z [V4L2:AUTO] (INFO) search for usable video devices
> 2021-03-29T18:03:52.644Z [V4L2:AUTO] (INFO) test v4l device: /dev/video0
> 2021-03-29T18:03:52.645Z [V4L2:AUTO] (INFO) Set device input to: Camera 1
> 2021-03-29T18:03:52.646Z [V4L2:AUTO] (INFO) Set resolution to: 1920 x 1080
> 2021-03-29T18:03:52.647Z [V4L2:AUTO] (INFO) Set framerate to 20 FPS
> 2021-03-29T18:03:52.647Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:99:GetSharedLut()) LUT folder location: '/usr/share/hyperhdr/lut'
> 2021-03-29T18:03:52.648Z [V4L2:AUTO] (INFO) Pixel format: MJPEG
> 2021-03-29T18:03:52.679Z [V4L2:AUTO] (INFO) found usable v4l2 device: /dev/video0 (USB Video: USB Video)
> 2021-03-29T18:03:52.681Z [V4L2:AUTO] (INFO) Started
> 2021-03-29T18:03:52.681Z [V4L2:auto] (DEBUG) (GrabberWrapper.cpp:48:start()) Grabber start()
> 2021-03-29T18:03:52.401Z [BOBLIGHT] (DEBUG) (BoblightServer.cpp:27:BoblightServer()) Instance created
> 2021-03-29T18:03:52.682Z [HYPERHDR] (INFO) Hyperhdr instance 'First LED Hardware instance' has been started
> 2021-03-29T18:03:52.401Z [COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) LED device: enabled
> 2021-03-29T18:03:52.402Z [EFFECTENGINE] (INFO) Run effect "Rainbow swirl fast" on channel 0
> 2021-03-29T18:03:52.424Z [EFFECTENGINE] (DEBUG) (EffectEngine.cpp:153:runEffectScript()) Start the effect: name [Rainbow swirl fast], smoothCfg [2]
> 2021-03-29T18:03:52.424Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:162:registerInput()) Register new input 'System/EFFECT' with priority 0 as inactive
> 2021-03-29T18:03:52.424Z [HYPERHDR] (INFO) Initial foreground effect 'Rainbow swirl fast' started
> 2021-03-29T18:03:52.444Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:252:setInputImage()) Priority 0 is now active
> 2021-03-29T18:03:52.444Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:378:setCurrentTime()) Set visible priority to 0
> 2021-03-29T18:03:52.444Z [IMAGETOLED] (INFO) Total index number for instance: 0 is: 320. Sparse processing: disabled, image size: 80 x 45, area number: 1
> 2021-03-29T18:03:52.444Z [IMAGETOLED] (INFO) Total index number for instance: 0 is: 320. Sparse processing: disabled, image size: 80 x 45, area number: 1
> 2021-03-29T18:03:52.444Z [SMOOTHING] (INFO) Selecting smoothing config (2) => direct mode: false, pause: false, settlingTime: 200 ms, interval: 40 ms (25 Hz), updateDelay: 0 ms
> 2021-03-29T18:03:52.444Z [HYPERHDR] (DEBUG) (HyperHdrInstance.cpp:546:handlePriorityChangedLedDevice()) priority[0], previousPriority[255]
> 2021-03-29T18:03:52.444Z [HYPERHDR] (DEBUG) (HyperHdrInstance.cpp:556:handlePriorityChangedLedDevice()) new source available -> switch LED-Device on
> 2021-03-29T18:03:52.445Z [IMAGETOLED] (DEBUG) (ImageProcessor.cpp:180:setHardLedMappingType()) set hard led mapping to multicolor_mean
> 2021-03-29T18:03:52.633Z [FLATBUFSERVER] (INFO) Started on port 19400
> 2021-03-29T18:03:52.634Z [PROTOSERVER] (INFO) Started on port 19445
> 2021-03-29T18:03:52.634Z [WEBSERVER] (DEBUG) (WebServer.cpp:34:initServer()) Initialize Webserver
> 2021-03-29T18:03:52.636Z [WEBSERVER] (DEBUG) (WebServer.cpp:34:initServer()) Initialize Webserver
> 2021-03-29T18:03:52.664Z [WEBSERVER] (DEBUG) (WebServer.cpp:92:handleSettingsUpdate()) Apply Webserver settings
> 2021-03-29T18:03:52.664Z [WEBSERVER] (DEBUG) (WebServer.cpp:92:handleSettingsUpdate()) Apply Webserver settings
> 2021-03-29T18:03:52.665Z [WEBSERVER] (DEBUG) (WebServer.cpp:110:handleSettingsUpdate()) Set document root to: :/webconfig
> 2021-03-29T18:03:52.665Z [WEBSERVER] (DEBUG) (WebServer.cpp:110:handleSettingsUpdate()) Set document root to: :/webconfig
> 2021-03-29T18:03:52.665Z [WEBSERVER] (INFO) Started on port 8090 name 'HyperHDR Webserver'
> 2021-03-29T18:03:52.693Z [WEBSERVER] (DEBUG) (WebServer.cpp:176:handleSettingsUpdate()) Setup SSL certificate
> 2021-03-29T18:03:52.694Z [WEBSERVER] (DEBUG) (WebServer.cpp:192:handleSettingsUpdate()) Setup private SSL key
> 2021-03-29T18:03:52.694Z [WEBSERVER] (INFO) Started on port 8092 name 'HyperHDR Webserver'
> 2021-03-29T18:03:52.798Z [V4L2:AUTO] (DEBUG) (V4L2Grabber.cpp:1140:process_image()) Worker's thread count  = 4
> 2021-03-29T18:03:52.833Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:252:setInputImage()) Priority 240 is now active
> 2021-03-29T18:03:55.450Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:271:clearInput()) Removed source priority 0
> 2021-03-29T18:03:55.450Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:378:setCurrentTime()) Set visible priority to 240
> 2021-03-29T18:03:55.454Z [IMAGETOLED] (INFO) Total index number for instance: 0 is: 165120. Sparse processing: disabled, image size: 1920 x 1080, area number: 1
> 2021-03-29T18:03:55.455Z [SMOOTHING] (INFO) Selecting smoothing config (0) => direct mode: false, pause: false, settlingTime: 150 ms, interval: 12 ms (83 Hz), updateDelay: 0 ms
> 2021-03-29T18:03:55.455Z [HYPERHDR] (DEBUG) (HyperHdrInstance.cpp:546:handlePriorityChangedLedDevice()) priority[240], previousPriority[0]
> 2021-03-29T18:03:55.456Z [IMAGETOLED] (DEBUG) (ImageProcessor.cpp:180:setHardLedMappingType()) set hard led mapping to multicolor_mean
> 2021-03-29T18:03:55.461Z [IMAGETOLED] (INFO) Total index number for instance: 0 is: 165120. Sparse processing: disabled, image size: 1920 x 1080, area number: 1
> 2021-03-29T18:03:55.461Z [EFFECTENGINE] (INFO) Effect 'Rainbow swirl fast' has finished.
> 2021-03-29T18:03:55.461Z [EFFECTENGINE] (INFO) Deleting effect named: 'Rainbow swirl fast'
> 2021-03-29T18:04:34.891Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.0.134
> 2021-03-29T18:04:34.893Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:85:handleInstanceSwitch()) Client '::ffff:192.168.0.134' switch to HyperHDR instance 0
> 2021-03-29T18:04:34.991Z [DB] (INFO) Database opened: /home/pi/.hyperhdr/db/hyperhdr.db
> 2021-03-29T18:04:52.659Z [V4L2:AUTO] (INFO) Video FPS: 15.75, av. delay: 52ms, good: 945, bad: 0 (60.02,15)
> 2021-03-29T18:04:53.401Z [LEDDEVICE] (DEBUG) (LedDeviceFile.cpp:85:close()) File: /dev/null
> 2021-03-29T18:04:53.402Z [LEDDEVICE] (INFO)  Stopped LedDevice 'file'
> 2021-03-29T18:04:53.403Z [LEDDEVICE] (INFO) Start LedDevice 'ws281x'.
> 2021-03-29T18:04:53.403Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:149:init()) deviceConfig: [{"colorOrder":"rgb","currentLedCount":300,"dma":5,"gpio":18,"hardwareLedCount":300,"invert":false,"latchTime":0,"leds":300,"pwmchannel":0,"rewriteTime":1000,"rgbw":false,"type":"ws281x","whiteAlgorithm":"subtract_minimum"}]
> 2021-03-29T18:04:53.404Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:408:setLatchTime()) LatchTime updated to 0ms
> 2021-03-29T18:04:53.404Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:429:setRewriteTime()) Refresh interval = 1000ms
> 2021-03-29T18:04:53.404Z [LEDDEVICE] (DEBUG) (LedDevice.cpp:435:setRewriteTime()) RewriteTime updated to 1000ms
> 2021-03-29T18:04:53.404Z [LEDDEVICE] (DEBUG) (LedDeviceWS281x.cpp:59:init()) ws281x strip type : 1050624
> 2021-03-29T18:04:53.406Z [SMOOTHING] (WARNING) Detect size changed. Previuos value: 1, new value: 300
> 2021-03-29T18:04:53.406Z [COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) LED device: disabled
> 2021-03-29T18:04:53.407Z [LEDDEVICE] (ERROR) Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: mmap() failed'
> 2021-03-29T18:05:08.116Z [IMAGETOLED] (INFO) Total index number for instance: 0 is: 537600. Sparse processing: disabled, image size: 1920 x 1080, area number: 300
> 2021-03-29T18:05:08.118Z [RgbTransform] (DEBUG) (RgbTransform.cpp:36:init()) RGB transform classic_config: 0, saturationGain: 1.000000, luminanceGain: 1.000000
> 2021-03-29T18:05:08.118Z [RgbTransform] (DEBUG) (RgbTransform.cpp:36:init()) RGB transform classic_config: 0, saturationGain: 1.000000, luminanceGain: 1.000000
> 2021-03-29T18:05:08.119Z [ChannelAdjust_RED] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:05:08.119Z [ChannelAdjust_BLUE] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:05:08.119Z [ChannelAdjust_GREEN] (DEBUG) (RgbChannelAdjustment.cpp:38:setCorrection()) set color correction to 255
> 2021-03-29T18:05:16.502Z [LEDDEVICE] (ERROR) Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: mmap() failed'
> 2021-03-29T18:05:52.668Z [V4L2:AUTO] (INFO) Video FPS: 19.88, av. delay: 39ms, good: 1193, bad: 0 (60.01,15)
> 2021-03-29T18:06:46.510Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:1080:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.0.134

#### Steps to reproduce
Raspberry Pi 4 2GB Rev 1.4
#### What is expected?
Able to open ws281x LED Hardware without any issues
#### What is actually happening?
Failed to open ws281x LED Hardware
#### System

> HyperHDR Server: 
> - Build:           (HEAD detached at caaceec) (Awawa-7d37aa4/caaceec-1614632873)
> - Build time:      Mar  1 2021 21:37:44
> - Git Remote:      https://github.com/awawa-dev/HyperHDR
> - Version:         15.0.0.0
> - UI Lang:         auto (BrowserLang: en-US)
> - UI Access:       expert
> - Avail Capt:      v4l2
> - Database:        read/write
> 
> HyperHDR Server OS: 
> - Distribution:   Raspbian GNU/Linux 10 (buster)
> - Architecture:   arm
> - CPU Model:      ARMv7 Processor rev 3 (v7l)
> - CPU Type:       Raspberry Pi 4 Model B Rev 1.4
> - CPU Revision:   b03114
> - CPU Hardware:   BCM2711
> - Kernel:         linux (5.10.17-v7l+ (WS: 32))
> - Qt Version:     5.11.3
> - Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0

**Comment by awawa-dev** [comment]
Seems that it's typical symptom of attempting to use ws281x driver without root privileges. As it's not mandatory for SPI mode, root must be provided for PWM mode. Please refer to following topis and report back if it helped: https://github.com/awawa-dev/HyperHDR/discussions/43

**Comment by weitheng** [comment]
Thanks, that fixed the problem! :)

**Comment by DedMsk** [comment]
ssh to raspberry

sudo systemctl disable --now hyperhdr@pi
sudo systemctl enable --now hyperhdr@root
sudo reboot
