### ISSUE TITLE
Need option to use system libs for build

### ISSUE THREAD

**Issue by Vascom** [awawa-dev/HyperHDR#524]
## Feature request

Please add options for cmake to build HyperHDR with system libs like flatbuffers, mbedtls and qmqtt.
Fedora rules requred unbundle as much as possible.

#### What problem does this feature solve?
Build HyperHDR for Fedora and add to official repo.

#### How should this be implemented in your opinion?
Change CMakeLists.txt file.

#### Are you willing to work on this yourself?
No. I don't know cmake build system.

**Comment by awawa-dev** [comment]
Hi
flatbuffers and mbedtls are critical core libraries for HyperHDR, each version must be tested before upgrading and I don't see possibilities to rely on system libs here. For example current mbedtls 3.3 causing problems for webos. qmqtt also needed some modification to build configuration to make it work also with Qt6 (its CMakeLists.txt is hardlinked to Qt5) but qmqtt is not critical component and can be disabled cmake configuration option.

**Comment by Vascom** [comment]
Thanks for clarification.

**Comment by awawa-dev** [comment]
This PR should bring support for Fedora: https://github.com/awawa-dev/HyperHDR/pull/591
