### ISSUE TITLE
Led goes off on fullscreen apps at wayland/pipewire

### ISSUE THREAD

**Issue by artempl** [awawa-dev/HyperHDR#534]
#### Steps to reproduce
Fedora, Wayland, Gnome DE

Switch any app like mpv or kodi to fullscreen

#### What is expected?

Led continues working

#### What is actually happening?

Led goes off
[console-output.txt](https://github.com/awawa-dev/HyperHDR/files/11048006/console-output.txt)

#### System

HyperHDR Server: 
- Build:           (HEAD detached at v19.0.0.0) (Awawa-3141e80/b8c7f04-1676222403)
- Build time:      Feb 12 2023 17:22:58
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         19.0.0.0
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Fedora Linux 37 (Workstation Edition)
- Architecture:   x86_64
- CPU Model:      AMD Ryzen 5 3600 6-Core Processor
- CPU Type:       113
- Kernel:         linux (6.1.18-200.fc37.x86_64 (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by artempl** [comment]
UPD. Fedora 38 Gnome 44.0 - same behavior - no lights for fullscreen apps only
Fedora 38 Gnome 44.1 - no lights for any case

**Comment by awawa-dev** [comment]
It's only a side-effect. The real cause is missing video stream in the pipewire capturing. Unfortunately this API has somedrawback, especially when the video acceleration is used. Still it's not a HyperHDR issue.

**Comment by awawa-dev** [comment]
@artempl you can try latest PR that implements hardware acceleration for capturing Wayland using Pipewire https://github.com/awawa-dev/HyperHDR/pull/556 Still it's up the Pipiwire to provide valid video stream and don't break (or at least start the auto-resume procedure) it e.g. when the application switch the video mode.
