### ISSUE TITLE
hyperhdr-remote --configGet not working

### ISSUE THREAD

**Issue by Thinner77** [awawa-dev/HyperHDR#535]
#### Steps to reproduce
./hyperhdr-remote --configGet --print

#### What is expected?
output of current config

#### What is actually happening?
output is:
hyperhdr-remote:
        Version   : 20.0.0.0beta0 (master (GitHub-bc24df7/a9a00f9-1678986833))
        build time: Mar 23 2023 11:04:11
Connected to: "127.0.0.1:19444"
Get configuration file from HyperHDR Server
Command: {"command":"config","subcommand":"getconfig"}
Reply: {"command":"config-getconfig","info":{"backgroundEffect":{"color":[255,138,0],
...
No configuration file available in result

**cause:**
config is sent in key "info" but JsonConnection.cpp::getConfig() checks for key "result"

```
QString JsonConnection::getConfig(std::string type)
{
	assert(type == "schema" || type == "config");
	qDebug() << "Get configuration file from HyperHDR Server";

	// create command
	QJsonObject command;
	command["command"] = QString("config");
	command["subcommand"] = (type == "schema") ? QString("getschema") : QString("getconfig");

	// send command message
	QJsonObject reply = sendMessage(command);

	// parse reply message
	if (parseReply(reply))
	{
		if (!reply.contains("result") || !reply["result"].isObject())
		{
			throw std::runtime_error("No configuration file available in result");
		}

		QJsonDocument doc(reply["result"].toObject());
		QString result(doc.toJson(QJsonDocument::Indented));
		return result;
	}

	return QString();
} 
``` 

#### System

HyperHDR Server: 
- Build:           master (GitHub-bc24df7/a9a00f9-1678986833)
- Build time:      Mar 23 2023 09:35:26
- Git Remote:      https://github.com/awawa-dev/HyperHDR.git
- Version:         20.0.0.0beta0
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (6.1.19+ (WS: 32))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by awawa-dev** [comment]
Fixed

**Comment by Thinner77** [comment]
Hi,

many thank for your really quick reply and fix.

wbr
