### ISSUE TITLE
WebUI: Set V4L device input

### ISSUE THREAD

**Issue by Thinner77** [awawa-dev/HyperHDR#537]
#### What problem does this feature solve?
Setting the V4L device input (Composite/S-Video) in Web UI, currently device input 0 (Composite) is set and can't be changed. 

#### What does the proposed API look like?
I don't know

#### How should this be implemented in your opinion?
restore original code

#### Are you willing to work on this yourself?
Maybe, a log-level "Trace" there all functions log there begin and end would be nice and helpfull to get knowledge of code flow. grabber.js seems to be a good starting point, but it doesn't get loaded in Firefox Developer Tools (F12)

**Comment by awawa-dev** [comment]
For old analog grabbers I think you can set it like PAL or SECAM using v4l2 tools https://github.com/awawa-dev/HyperHDR/pull/423
Currently, I do not plan further development in this direction.
