### ISSUE TITLE
LED hang after a few minutes.

### ISSUE THREAD

**Issue by R3PTIL3** [awawa-dev/HyperHDR#546]
FULL LOG
https://pastebin.com/FLfcYBKC

Steps to reproduce
Start HyperHDR and after a few minutes the problem comes.

What is actually happening?
LED hang after a few minutes. No more control over the led strip only a restart of the Raspberry Pi helps then.

System
HyperHDR Server:

Build: (HEAD detached at v19.0.0.0) (Awawa-3141e80/b8c7f04-1676222403)
Build time: Feb 12 2023 17:40:44
Git Remote: https://github.com/awawa-dev/HyperHDR
Version: 19.0.0.0
UI Lang: auto (BrowserLang: de)
UI Access: default
Avail Capt: Linux (V4L2)
Database: read/write
HyperHDR Server OS:

Distribution: Debian GNU/Linux 11 (bullseye)
Architecture: arm64
CPU Type: Raspberry Pi 4 Model B Rev 1.5
CPU Revision: c03115
CPU Hardware: BCM2835
Kernel: linux (5.15.61-v8+ (WS: 64))
Qt Version: 5.15.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62

USB3.0 UHD: USB3.0 UHD (video0) MS2130
1280x720x60 YUYV
awa_spi
SK6812CW
ESP32 Live D1Mini
SN74AHCT125N Shifter
Mean Well LRS-100-5

**Comment by awawa-dev** [comment]
Hi
I dont see a problem in HyperHDR logs. What is your power supply for Rpi? When that happens is HyprHDR is accessible? If so if enable/disable LED driver resolve the problem? Or reset of ESP32?

**Comment by R3PTIL3** [comment]
Hello, thank you for the Feedback.
The power Supply for the Raspberry is the original power Supply with 3A.  
The Page is reachable but the LEDs can't be turned off, they stay on. Frozen
The ESP32 I unfortunately do not know how to reset it. I help myself then with the restart of the Raspberry. 

Yes the ESP32 is connected to the USB port of Rpi.

**Comment by awawa-dev** [comment]
On your version of ESP32 board don't you have a button to reset it?

**Comment by R3PTIL3** [comment]
Yes now that you say it the button exists.

**Comment by awawa-dev** [comment]
So when it hangs again use it to see if it starts to respond after few seconds.

**Comment by R3PTIL3** [comment]
Hello, yes the reset on the ESP helps and the LED strips respond again. Until the next hang up.

**Comment by awawa-dev** [comment]
Please upload your HyperHDR exported config. Please post a picture of your ESP32 model.
How do you connect ESP32 to Rpi pinout? Do you have a spare ESP32 to test it instead the current one? Since you have ESP32 connected to Rpi can you test also HyperSerialESP32 (should be build with similar settings for pinout as HyperSPI, if you have CH9102x then change speed for HyperHDR 4000000 and use it later in HyperHDR also)?

**Comment by R3PTIL3** [comment]
**Please upload your HyperHDR exported config.** 
[HyperHDR-19.0.0.0-Backup-2023-04-06.txt](https://github.com/awawa-dev/HyperHDR/files/11173910/HyperHDR-19.0.0.0-Backup-2023-04-06.txt)

**Please post a picture of your ESP32 model.**

![IMG_2201](https://user-images.githubusercontent.com/17035078/230483196-24a4ba97-a94f-4094-9c6a-bf1aed64f6de.jpg)
![IMG_2200](https://user-images.githubusercontent.com/17035078/230483230-d22de24b-0910-425f-ac90-2e133d939d3f.jpg)

**How do you connect ESP32 to Rpi pinout?**
_ESP32	/	Raspberry Pi 4 
GPIO 2	/	LED out 1
GPIO 4	/	LED out 2
GPIO 5	/	24 SPI0 CE0
GPIO 18	/	23 SPI SCLK
GPIO 19	/	21 SPI0 MISO
GPIO 23 	/        19 SPI0 MOSI
GND	/	20 GND_

**Do you have a spare ESP32 to test it instead the current one?**
_No unfortunately not at the moment new ones are still on the way._

**Since you have ESP32 connected to Rpi can you test also HyperSerialESP32 (should be build with similar settings for pinout as HyperSPI, if you have CH9102x then change speed for HyperHDR 4000000 and use it later in HyperHDR also)?**
_I will test it tomorrow._

**Comment by awawa-dev** [comment]
Any progress on diagnosis using HyperSerialESP32 or HyperSPI?
