### ISSUE TITLE
Possibility to import v16 backup

### ISSUE THREAD

**Issue by HorizonKane** [awawa-dev/HyperHDR#551]
#### What problem does this feature solve?
The need to reconfigure everything after upgrading from v16.

I saved my settings and upgraded my Pi to Bullseye to install v19. Now I learn that I can't import the settings.

#### How should this be implemented in your opinion?

At least the settings for LEDs and so on should be imported so I dont need to configure everything again. I also did not document my settings as I thought I have a backup....

**Comment by awawa-dev** [comment]
Hi
This is not an issue or bug:  v16 is not supported for a long time and there was an information about import/export re-implemented when v17 was introduced (the old one was completely broken and allowed only one instance export/import). Still if you have your backup JSON from v16 you can restore v16 SD image, restore v16 exported JSON backup and when you restore it then export the database from e.g. /home/pi/.hyperhdr/db folder. Then install v17 SD image and restore this database. Now you can export v17 JSON using HyperHDR page and import it in v18 or v19 later if you want.

**Comment by HorizonKane** [comment]
Thank you for the fast reply.

I see. I will just reconfigure my LEDs then.

Thank you for your great work here! Your put so much effort in this!
