### ISSUE TITLE
ws2812, wled and HyperHDR - not all lights work in HyperHDR

### ISSUE THREAD

**Issue by JayJay-SmartHome** [awawa-dev/HyperHDR#562]
I have the above set up behind the tv in the family room.

Rpi zero 2 - handles the hyperhdr - using 19.0.0.0beta2
Nodemcu handles the ws2812 lights and wled

As it is, the wled set up is perfect - all the lights work (176 leds)

Lights start bottom centre-ish going clockwise as you face the front of the tv location 109
34 leds from Centre to left 
33 leds from bottom left to top left
57 leds from top left to top right
33 leds from top right to bottom right 
And 19 leds from bottom right to centre
And there’s a gap of what could be 4 leds if I had carried on (gap of 4 at location 109)
All in all there is 176 leds plus the gap

As I said, in wled it all lights up fine, however in hyperhdr only the first 172 leds work

yes

#### Steps to reproduce
?

#### What is expected?
All 176 lights to work

#### What is actually happening?
In HyperHDR only the 1st 172 LEDs work the 4 remaining either are off or are pulling the lights from WLED.

#### System

System info

HyperHDR Server: 
- Build:           (HEAD detached at v19.0.0.0beta2) (GitHub-03ed5dc/4d78188-1670856973)
- Build time:      Dec 12 2022 15:27:27
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         19.0.0.0beta2
- UI Lang:         en (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi Zero 2 W Rev 1.0
- CPU Revision:   902120
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.61-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Comment by awawa-dev** [comment]
And screenshot of your LED strip geometry from HyperHDR page? UDPraw or WLED driver?

**Comment by JayJay-SmartHome** [comment]
> And screenshot of your LED strip geometry from HyperHDR page? UDPraw or WLED driver?

![image](https://github.com/awawa-dev/HyperHDR/assets/68328562/6da583bc-d950-4f8f-a1a7-cdf87b790242)

**Comment by JayJay-SmartHome** [comment]
Does this help?

**Comment by awawa-dev** [comment]
Could you take a screenshot of whole tab section including your provided values and calculated amperage (it includes total LEDs number)?

**Comment by JayJay-SmartHome** [comment]
>![image](https://github.com/awawa-dev/HyperHDR/assets/68328562/c75df303-4198-419d-9f40-601a4b55b724)
![image](https://github.com/awawa-dev/HyperHDR/assets/68328562/f47529d9-f14e-4e60-b199-5b484c152031)

**Comment by awawa-dev** [comment]
Thank you. Did you restart HyperHDR after you created/modified the LED geometry?

**Comment by JayJay-SmartHome** [comment]
I think I did...
Will check later and let you know my findings...

**Comment by awawa-dev** [comment]
I think I found it: initially could not reproduce the problem for your configuration but then I changed the LEDs number and still the application remembered the first number. Restart solved it. Prepared a small patch to fix it.

**Comment by JayJay-SmartHome** [comment]
Yes restart solved it
Thank you
