### ISSUE TITLE
Add Option for GPIO pin to control relay like WLED 

### ISSUE THREAD

**Issue by vegedb** [awawa-dev/HyperHDR#578]
# WLED Options

![image](https://github.com/awawa-dev/HyperHDR/assets/72070424/415ceea5-7a56-4203-a3ee-19f9d850b018).

Current Setup: 
1) (Raspberry Pi 4) GPIO18 is used for LED Data Pin
2) Separate 12V Power Supply for LED's 12V+GND

Feature Request:
3) Use 3.3v/5v relay (GPIO 15) to switch/relay 12v Power Supply [AC SIDE]
![image](https://github.com/awawa-dev/HyperHDR/assets/72070424/dada9d0f-05a4-47bf-8fc4-565c8fc03af3)

As you can see (screenshot), WLED has this feature already inbuilt in the software. It would be great if you implement this feature. 

Addressable Strips around 55" TV, measured 6-7W idle when LED's are turned OFF! 
This is the same power used on a raspberry pi 4 by itself!!!

**Comment by awawa-dev** [comment]
Hi
Controlling Neopixel directly from current Rpi models is not and will not be officially supported due to the many issues it usually causes, so I see no reason to implement such a companion feature in HyperHDR. Potentially such a solution could be added to some of my HyperSerial projects. If you have one of the supported boards (esp32/esp32-s2 mini/rp2040) and will provide testing and feedback, please open a feature request in one of these projects.

**Comment by vegedb** [comment]
>Controlling Neopixel directly from current Rpi models is not and will not be officially supported due to the many issues it usually causes, so I see no reason to implement such a companion feature in HyperHDR.

wdym? It can be used using these setting. GPIO 18
![image](https://github.com/awawa-dev/HyperHDR/assets/72070424/cc2e6424-fcdf-4430-9d8b-065482f801ef)
![image](https://github.com/awawa-dev/HyperHDR/assets/72070424/475694cd-0776-4e4c-9818-773e45a567d9)

**Comment by awawa-dev** [comment]
I left it only for backward compatibility for advanced users. Please read the faq or https://github.com/awawa-dev/HyperHDR/discussions/320

**Comment by awawa-dev** [comment]
If the next generation of the Rpi5 includes a PIO coprocessor like the one built into the rp2040, the implementation of the control relay may be reconsidered.

**Comment by chasecee** [comment]
@awawa-dev is it possible (or smart) to use a separate WLED relay system just for managing power of LEDs?

**Comment by awawa-dev** [comment]
@chasecee  I think so. HyperSerialESP32 also supports relay control. Alternatively you can use smart-sockets.
