### ISSUE TITLE
JSON API to get a screenshot and/or current dominant color.

### ISSUE THREAD

**Issue by Cheerpipe** [awawa-dev/HyperHDR#602]
#### What problem does this feature solve?
I am trying to get and download a screen capture of what is processed by hyperHDR. I want this to create a dominant color sensor on Home Assistant.

Another aproach could be get an JSON API to expose the current dominant color value.

#### What does the proposed API look like?
What i am looking for is an JSON API that return the the current image being processed by HyperHDR (Like the Live "Screenshot" feature of the GUI.)

#### How should this be implemented in your opinion?
n/a

#### Are you willing to work on this yourself?
Should learn C/C++.

**Comment by awawa-dev** [comment]
Hi
How often do you plan to execute it? I'm afraid this is the perfect backdoor to kill HyperHDR/RPi with overload as such a potential command is not guarded and averaging over the whole image (or returning the image as a string/base64 encoded in the JSON result) is very time consuming? Alternatively, the average color of the LEDs for the selected instance?

**Comment by Cheerpipe** [comment]
Hi Awawa, thanks for your fast response.

I want to execute this just on certain media_player state changes (Ex: to playing, to pause and track changed) using the built in home assistant color quantizer.

Also like the idea to get the average color of leds for a specific instance instance. It should works well and it is cheaper for the cpu cause i may create a instance with just a few leds to make the math easier.

**Comment by awawa-dev** [comment]
Implemented in https://github.com/awawa-dev/HyperHDR/pull/611
