### ISSUE TITLE
Ability to change MQTT Topic.

### ISSUE THREAD

**Issue by xZetsubou** [awawa-dev/HyperHDR#619]
#### What problem does this feature solve?
The issue is that if I have multi HyperHDR server in my network connected to the same MQTT Server they will all share the same topic `HyperHDR/JsonAPI`, trigger an action will trigger all HyperHDR servers

> More FR tho it's not so important, It will be even more useful I can specify the instance index through the topic, 
> HyperHDR/0/JsonAPI # Instance 0
> HyperHDR/1/JsonAPI # Instance 1

#### How should this be implemented in your opinion?
Add a textbox in MQTT Config tab to modify main topic
```
{var_mqtt_topic}/JsonAPI 
{var_mqtt_topic}/JsonAPI/response
```
#### Are you willing to work on this yourself?
Haven't code c++ before but I can help if needed

**Comment by awawa-dev** [comment]
PR implementing custom MQTT topic: https://github.com/awawa-dev/HyperHDR/pull/620
Temporarily installers are available here for a while:: https://github.com/awawa-dev/HyperHDR/actions/runs/5813337111
Please test it and let me know if it works OK. I think we leave the direct instance channel for HyperHDR v21 as there is an option to switch instances using JsonAPI.

**Comment by xZetsubou** [comment]
I just tested it and it works perfectly good .

Thank you.
