### ISSUE TITLE
HyperHDR - WLED - Screen capture no longer working

### ISSUE THREAD

**Issue by ahajalie** [awawa-dev/HyperHDR#634]
#### Steps to reproduce
Start HyperLED. Observe boot effect. Leds then turn off. Screen capture is enabled in settings.

#### What is expected?
LEDs should be on 

#### What is actually happening?
Leds turn off.

#### System

HyperHDR Server: 
- Build:           (HEAD detached at b8c7f04) (Awawa-3141e80/b8c7f04-1676222403)
- Build time:      Feb 12 2023 17:25:03
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         19.0.0.0
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 11 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.22621 (WS: 64))
- Qt Version:     6.2.4
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

**Comment by awawa-dev** [comment]
The issue template mentions about mandatory full logs no without the reason and I dont' know any HyperLED that I can help with either. Please respect our time.
