### ISSUE TITLE
DirectStream Input (OBS Virtual Webcam)?

### ISSUE THREAD

**Issue by SaulGoodman1337** [awawa-dev/HyperHDR#67]
#### What problem does this feature solve?
Looking for a way to feed Hyperion with OBS data I finally ended up with USB Grabber again. 
I also talked to the developers of Hyperion but they don't seem to be interested in optimizing the software for PC gaming. 

Anyway, I found this project here by chance and was enthusiastic from the beginning. Interesting I found the possibility of ScreenRecording using microsoft media foundation. 
Finally it is possible purely by software to enjoy my Ambilight with Doom (Vulkan)!!! No other grabber could offer me this up to here! Yes I know, it is not perfect ... but therefore also the request here to work on integrating OBS.

#### How should this be implemented in your opinion?
One possibility would be for example with OBS Virtual Webcam (DirectStream). But you will with certainty 
#### Are you willing to work on this yourself?
I would, but I can't. That is a little too high for me

**Comment by awawa-dev** [comment]
Hi
OBS under Windows doesn't expose media foundation interface and it uses DirectShow instead. I used some other software that can create such interface using media foundation (for example to stream a video from mobile) so it's definitely possible but it seems OBS lags here. I know there is an issue on macOS with OBS: it's probably related to some missing video capture mode in HyperHDR but can't say more without provided logs.

I don't have a plan to implement any DirectX/Stream related capturing under Windows because it's legacy solution compared to Microsoft media foundation. But I do have a plan to create a plunging for OBS to send a stream to HyperHDR. Probably two major version away as a lot is going on in the HyperHDR developing right now and we lack of resource at the moment.

**Comment by SaulGoodman1337** [comment]
> 
> 
> Hi
> OBS under Windows doesn't expose media foundation interface and it uses DirectShow instead. I used some other software that can create such interface using media foundation (for example to stream a video from mobile) so it's definitely possible but it seems OBS lags here. I know there is an issue on macOS with OBS: it's probably related to some missing video capture mode in HyperHDR but can't say more without provided logs.
> 
> I don't have a plan to implement any DirectX/Stream related capturing under Windows because it's legacy solution compared to Microsoft media foundation. But I do have a plan to create a plugin for OBS to send a stream to HyperHDR. Probably two major version away as a lot is going on in the HyperHDR developing right now and we lack of resource at the moment.

Hi,
thank you for the answer and I am very happy to hear that you are working on a plugin for OBS !
For now I'll make do with OBS+ManyCam. That works quite well for now. 

Nevertheless, I have to ask a question that doesn't quite fit here. I do not understand the adjustment for HDR with the LUT file. Did I miss something or is there really no good tutorial for this? 
Do you have a forum where you can discuss something like that ?

**Comment by awawa-dev** [comment]
Almost all the users were using the default LUT table (previously you could only tweak the brightness) so there was little demand for better tutorial ;) There is some info in the manifest of the latest release as it brought new features related to the LUT table subject. If something is not clear you can ask here of course.

**Comment by SaulGoodman1337** [comment]
Hi,
thanks for offering to help me here.
I do not quite understand the LUT yet. As soon as I turn on HDR in Windows, everything appears white! Can you possibly help me here?

![hdr](https://user-images.githubusercontent.com/4953452/120771664-be29ca80-c51f-11eb-8942-c9b75a0c2700.PNG)

**Comment by awawa-dev** [comment]
Assuming that you are using the latest version  most probably the video stream to the grabber is not in fact HDR and it's captured by the grabber as SDR (SDR capturing works OK for almost all modern grabbers). In that case you don't need hdr tone mapping  because it leads to picture overexposed. You should take a look at the video preview before turning on HDR tone mapping in the HyperHDR and compare it to the examples on the main github hyperhdr page, how it should look before (tone mapping off) with colors washed-out and after (tune mapping on).

**Comment by SaulGoodman1337** [comment]
Then I don't quite understand how I can do HDR and still not have washed out colors?

**Comment by awawa-dev** [comment]
As I wrote, probably you dont have a hdr signal on the grabber input or its for example Ezcap 320 that can do partial tone mapping and it needs a special LUT table. Take a screenshot similar as above with turned OFF hdr tone mapping in hyperhdr assuming that you turned ON hdr in Windows 10. Then we will see if you need it.

**Comment by SaulGoodman1337** [comment]
> 
> 
> As I wrote, probably you dont have a hdr signal on the grabber input or its for example Ezcap 320 that can do partial tone mapping and it needs a special LUT table. Take a screenshot similar as above with turned OFF hdr tone mapping in hyperhdr assuming that you turned ON hdr in Windows 10. Then we will see if you need it.

Hi,
I have attached a screenshot.
![HDR1](https://user-images.githubusercontent.com/4953452/120904430-91270600-c64c-11eb-8048-8ffb4ee88847.png)

by the way:
I have changed the settings in the meantime. I got a cheap HDMI grabber for 5€ at Amazon (https://tinyurl.com/2nxm37tu). It is not the fastest, but for now it is okay for me. Until your OBS plugin comes I'm happy with it for now.
With OBS I make a full screen project on the HDMI grabber and get me from there the image via HyperHDR. 
I now have one less software...

**Comment by awawa-dev** [comment]
It's seems that the HyperHDR HDR tone mapping is still ON.
Please set if OFF  and then take a screenshot.
BTW it's classic example of unnecessary using of Hyperhdr HDR tone mapping on SDR source again.

> by the way:
> I have changed the settings in the meantime. I got a cheap HDMI grabber for 5€ at Amazon (https://tinyurl.com/2nxm37tu). > It is not the fastest, but for now it is okay for me. Until your OBS plugin comes I'm happy with it for now.

Probably it's MS2109 - many of our users use it with good results.

**Comment by SaulGoodman1337** [comment]
> 
> 
> It's seems that the HyperHDR HDR tone mapping is still ON.
> Please set if OFF and then take a screenshot.
> BTW it's classic example of unnecessary using of Hyperhdr HDR tone mapping on SDR source again.
> 
> > by the way:
> > I have changed the settings in the meantime. I got a cheap HDMI grabber for 5€ at Amazon (https://tinyurl.com/2nxm37tu). > It is not the fastest, but for now it is okay for me. Until your OBS plugin comes I'm happy with it for now.
> 
> Probably it's MS2109 - many of our users use it with good results.

Tone mapping is off... this comes from OBS... :(
![HDR1](https://user-images.githubusercontent.com/4953452/120907994-9bee9480-c666-11eb-9e0c-b6004150379f.png)

**Comment by awawa-dev** [comment]
From what I found OBS doesn't support system HDR unfortunately. Maybe that it manifests?

**Comment by SaulGoodman1337** [comment]
I'm a little confused myself.
I remember some time ago I tried to record my HDR screen with OBS. 
And here I had a rather dark image with washed out colors. Actually exactly what we expect here ?

I don't know why I get this bright image instead. 

Do you have an alternative idea how I can enjoy HyperHDR with Windows 10 and HDR ?

**Comment by awawa-dev** [comment]
Probably they are working to implement it. But it seems OBS captured already SDR stream and then they apply tone mapping unnecessary. Try to downgrade OBS a year or so (uninstall also that virtual camera first)? Other solution is to use USB grabber.

**Comment by SaulGoodman1337** [comment]
I'm going to try this with a downgrade.

Yes but USB Grabber looks at Displayport with HDR and 170hz, freesync etc probably rather bad or?
I think here it goes from the frying pan into the fire....

**Comment by awawa-dev** [comment]
Dont know of any grabber works with gsync or freesync.
170hz propably is also too much for MS2109.
Only Ezcap 320 supports quite high framerate: 2160p60, 1440p144, 1080p240. At least on the paper.

**Comment by SaulGoodman1337** [comment]
the MS2109 is actually okay for now.
I had hoped that I could simply duplicate the image. 
I wanted to run the grabber at 720p/60hz and my monitor at 1440p/170hz and then just clone.
But that doesn't really seem possible with Windows/Nvidia like that. This is possible but the Windows UI lags terribly... 

Here is a video of my current method which only works without HDR:
OBS Projection to HDMI Grabber -> HyperHDR.


https://user-images.githubusercontent.com/4953452/121016289-3bfa0a00-c79c-11eb-8622-66bd317ebe7e.mp4


You can see that it is slightly delayed but it's totally okay for me
I'll just have to keep trying....

**Comment by awawa-dev** [comment]
Try to disable smoothing because with wrong settings (not corresponding to the led driver capability) it could affects performance. Black bar border detection is nonessential also.
Try lower resolution in OBS' camera and especially lowering framerate is a must (from the list or use frame rate decimation option). Force different video encodings if available. Probably that virtual camera has to make a color space conversion before streaming and then we have to make another conversion in HyperHDR: some encodings could work better in that situation.

**Comment by SaulGoodman1337** [comment]
Hi,
I wanted to let you know something. I had a look at the Windows 11 Preview today and found out that it is possible to mirror the 165hz screen with a USB grabber display without any jerky effects on the 165hz screen.
It seems that Microsoft finally fixed this annoying bug with Wddm 3.0 !

I'll have to try the whole thing with a virtual display...

**Comment by awawa-dev** [comment]
Many changed from this time, and HyperHDR currently offers software screen grabbers for every OS. If a new interesting functionality would appear in OBS, I would again re-consider creating a plugin. I am closing the issue for now.
