### ISSUE TITLE
Add the "Image flip" setting from Hyperion to USB Capture function

### ISSUE THREAD

**Issue by BlackBulletBrony** [awawa-dev/HyperHDR#676]
#### What problem does this feature solve?
Adding the "Image flip" setting from Hyperion to USB Capture function to adjust the flipping of the input image.

#### What does the proposed API look like?
I am not qualified in this field.

#### How should this be implemented in your opinion?
For example, like in Hyperion.
![2023-11-24_16-49-46](https://github.com/awawa-dev/HyperHDR/assets/51234766/1f935164-6060-4bb5-93a8-1bb7cb678877)

#### Are you willing to work on this yourself?
Unfortunately, I don't have the necessary skills.

**Comment by awawa-dev** [comment]
Hi
Modern HDMI grabbers do not need this legacy option, which could theoretically be useful for old analog grabbers from another era. None of the many mainline USB grabbers I tested need it, and its implementation would require making/testing changes in as many as 3 systems (windows/macos/linux), so I don't see any free resources I could allocate to it.
