### ISSUE TITLE
After Compiling cloning the latest git keep getting version 16.0.0.0

### ISSUE THREAD

**Issue by appleimperio** [awawa-dev/HyperHDR#70]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

HyperHDR Server: 
- Build:           master (Awawa-db04b19/4e6999e-1621522708)
- Build time:      Jun  4 2021 01:03:17
- Git Remote:      https://github.com/awawa-dev/HyperHDR.git
- Version:         16.0.0.0
- UI Lang:         auto (BrowserLang: en-us)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

#### Steps to reproduce
compiling following your step in a fresh system
#### What is expected?
version 16.0.0.1

**Comment by awawa-dev** [comment]
You can always find a source for the release commit at the release page.
![obraz](https://user-images.githubusercontent.com/69086569/120837123-a295e280-c566-11eb-8471-9105155a69a7.png)
So to have v16.0.0.1 with includes hotfix for v16 after the master branch went forward, just switch to the ````v16.0.0.1```` branch instead of master.

**Comment by appleimperio** [comment]
Thanks for your help instead of this command "git clone --recursive https://github.com/awawa-dev/HyperHDR.git" what should I use to include the hotfix?

**Comment by awawa-dev** [comment]
Use standard ````git checkout <brench>```` to switch for v16.0.0.1 brench.
So it goes:
```` 
git clone --recursive https://github.com/awawa-dev/HyperHDR.git <some dir>
cd <some dir>
git checkout  v16.0.0.1
````

That's all.

**Comment by appleimperio** [comment]
Awesome Thank you!!!!

**Comment by awawa-dev** [comment]
Sorry, too fast: v16.0.0.1 is a tag of course
so use ````git checkout  tags/v16.0.0.1````

**Comment by appleimperio** [comment]
I create a Dockerfile and its working great. I been using it for about 9 month and jut updated to the latest version. I use it on a Raspberry PI with a 64 bit system. If you are interested I can send you the file so you can take a look and maybe improve it. Thanks for your help again got it running.

**Comment by awawa-dev** [comment]
I'm not an expert of docker unfortunately ;) BTW seems a lot of people are using arch64. Maybe I will include it in the next release and remove x64 RPM to not cross the github space quote.

**Comment by appleimperio** [comment]
Great news!! Thank you!
