### ISSUE TITLE
apt install unmet dependencies for 20.0.0.0.bookworm.beta1-armv6l.deb

### ISSUE THREAD

**Issue by rorosaurus** [awawa-dev/HyperHDR#700]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

I'm following the installation wiki, but hit a snag when running apt install:

````
admin@hyperion:/tmp $ sudo apt install ./HyperHDR-20.0.0.0.bookworm.beta1-armv6l.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'hyperhdr' instead of './HyperHDR-20.0.0.0.bookworm.beta1-armv6l.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hyperhdr : Depends: libc6 (>= 2.36) but 2.31-13+rpt2+rpi1+deb11u7 is to be installed
            Recommends: shared-mime-info but it is not going to be installed
            Recommends: libp8-platform-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
````

#### Steps to reproduce
1. Install fresh bookworm image on Raspberry Pi 1.
2. SSH in and try to run `sudo apt install ./HyperHDR-20.0.0.0.bookworm.beta1-armv6l.deb`

#### What is expected?
`---> HyperHDR has been installed/updated!`

#### What is actually happening?
````
 hyperhdr : Depends: libc6 (>= 2.36) but 2.31-13+rpt2+rpi1+deb11u7 is to be installed
            Recommends: shared-mime-info but it is not going to be installed
            Recommends: libp8-platform-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
````
#### System

Raspberry Pi 1, the SD card is a fresh bookworm lite image, plugged in over ethernet and SSH'd in. This hardware probably isn't good enough, but I'm on a budget and want to see how bad it is! From what I can tell it is supported, but not recommended?

I have followed the same steps with 19.0.0.0 and it installed successfully.

**Comment by awawa-dev** [comment]
Hi
You are using bullseye with glibc 2.31. 
Bookworm glibc 2.36: https://packages.debian.org/source/bookworm/glibc
Bullseye glibc 2.31: https://packages.debian.org/source/bullseye/glibc
The safest way to install/update HyperHDR is APT repository: https://awawa-dev.github.io/

**Comment by rorosaurus** [comment]
Awesome, thanks! Perhaps we could link that github.io page on the linux installation wiki page? I would submit a request, but I think only contributors can edit the wiki.

**Comment by awawa-dev** [comment]
That's a very good idea, I missed it. Thank you.
I updated the wiki.
