### ISSUE TITLE
Black bar detect status on remote page not update, always disable status appear after HyperHDR startup - v20.0.0.0beta1

### ISSUE THREAD

**Issue by DonaldTrump-2020** [awawa-dev/HyperHDR#706]
#### Steps to reproduce

After activating this feature, it shows enabled on the remote page. But when restarting HyperHDR, it always switches back to disable status

#### What is expected?

The black bar detect status on the remote page displays the correct status

#### What is actually happening?

when restarting HyperHDR, Black bar detect always switches back to disable status

#### System
Windows 10 / v20.0.0.0beta1

**Comment by awawa-dev** [comment]
To make it permanent you need to enable blackbar detection in the processing tab. As it is explained on the remote tab, all switches/status are transient.

**Comment by DonaldTrump-2020** [comment]
> To make it permanent you need to enable blackbar detection in the processing tab. As it is explained on the remote tab, all switches/status are transient on that page.

I know what you mean. But this is a bug that even if I turn it on permanently in image processing > black bar detection, it still displays the wrong status after HyperHDR restarts.

**Comment by awawa-dev** [comment]
Now that you mentioned another tab, that changes things. Please check the latest build: https://github.com/awawa-dev/HyperHDR/actions/runs/7412874056

**Comment by DonaldTrump-2020** [comment]
> Now that you mentioned another tab, that changes things. Please check the latest build: https://github.com/awawa-dev/HyperHDR/actions/runs/7412874056

solved! thank you so much!
