### ISSUE TITLE
v20.0.0.0beta1 exported configuration backup fails on import with compatibility warning. 

### ISSUE THREAD

**Issue by jansene** [awawa-dev/HyperHDR#708]
## Bug report
Importing v20.0.0.0beta1 configuration export fails with:
The selected configuration file "backup.json" can't be imported. It's not compatible with HyperHDR v17 and higher!

#### Steps to reproduce
From UI export configuration
From UI import the previously saved configuration export

#### What is expected?
Successful import of saved configuration export xml file.
 
#### What is actually happening?
Import fails with file compatibility warning:
The selected configuration file "backup.json" can't be imported. It's not compatible with HyperHDR v17 and higher!

After editing the configuration export file by updating export format from v20 to v17,  the configuration import succeeds:
from: "version": "HyperHDR_export_format_v20"  to "version": "HyperHDR_export_format_v17"

#### System
HyperHDR Server: 
- Build:           v20rc (Awawa-7888631/5dfba84-1704389679)
- Build time:      Jan  4 2024 17:39:30
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0beta1
- UI Lang:         auto (BrowserLang: en-US)
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 5 (v7l)
- CPU Type:       Raspberry Pi 2 Model B Rev 1.1
- CPU Hardware:   a01041
- Kernel:         linux (6.1.21-v7+ (WS: 32))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

**Comment by awawa-dev** [comment]
Thank you 👍 Fixed: https://github.com/awawa-dev/HyperHDR/actions/runs/7420455457 https://github.com/awawa-dev/HyperHDR/pull/705
