### ISSUE TITLE
Cant install the package from the Official Linux repo

### ISSUE THREAD

**Issue by PartyPigy45** [awawa-dev/HyperHDR#738]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
When trying to install HyperHDR on linux mint, following the instructions gives an error when running `sudo apt update` with the following:
```
Err:15 https://awawa-dev.github.io virginia Release                             
  404  Not Found [IP: 185.199.109.153 443]
E: The repository 'https://awawa-dev.github.io virginia Release' does not have a Release file.
```

#### Steps to reproduce
Follow the instructions on the [Official Linux repo](https://awawa-dev.github.io/) aka:
```
type -p curl >/dev/null || sudo apt install curl -y
curl -fsSL https://awawa-dev.github.io/hyperhdr.public.apt.gpg.key | sudo dd of=/usr/share/keyrings/hyperhdr.public.apt.gpg.key \
&& sudo chmod go+r /usr/share/keyrings/hyperhdr.public.apt.gpg.key \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://awawa-dev.github.io $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperhdr.list > /dev/null \
&& sudo apt update
```
the error occors at this point so no need for the `sudo apt install hyperhdr -y`

#### What is expected?
It to find the package

#### What is actually happening?
Returns a 404

#### System
I cant access the web interface at this point

**Comment by awawa-dev** [comment]
And which distro are you using?

**Comment by PartyPigy45** [comment]
linux mint, saying that. I was able to install it through the .deb package

**Comment by awawa-dev** [comment]
Yes, the installers should work on many systems as long as the glibc version is compatible (the deb installer should check this).
For now, the repo only supports certain versions of Debian and Ubuntu.
