### ISSUE TITLE
Some Light Effects removed in V16.x

### ISSUE THREAD

**Issue by basesnow** [awawa-dev/HyperHDR#75]
## Feature request

I was running v14.x and there were a couple of light effects that I used with Home Assistant for notifications (specific effects I was using: system shutdown, sparks, fire, etc). I upgraded to v16.x and those effects are not longer available. Hoping that it is easy to bring back into the next release.

**Comment by awawa-dev** [comment]
Hi
You missed some important announcement from v15 https://github.com/awawa-dev/HyperHDR/releases/tag/v15.0.0.0
It was caused by completely removal of internal Python interpreter. Which effect you missed in v16/v15?

**Comment by basesnow** [comment]
Ah, yea. I only skimmed those notes since I jumped strait to v16. Thanks for pointing that out. Here were the effects I was using in order of importance. I understand if it isn't worth your time. These aren't game changers. But it was nice to utilize for notifications in home assistant 

1 System shutdown
2 Fire
3 Sparks

**Comment by awawa-dev** [comment]
I think that 'System shutdown' and 'Sparks' could come back in near future but don't know if in next, incoming release. 'Fire' effect is more complicated as it used some background gif so the chances for him are slim.

**Comment by basesnow** [comment]
Thanks, I appreciate you looking into. You do awesome work!

**Comment by awawa-dev** [comment]
'Sparks' and 'system shutdown' effects are implemented in version 17 (beta for testing).
If you have some time, please test it. Reopen the issue if needed.
https://github.com/awawa-dev/HyperHDR/releases/tag/v17.0.0.0beta
