### ISSUE TITLE
Color calibration assistant gone?

### ISSUE THREAD

**Issue by tommyguuuun** [awawa-dev/HyperHDR#772]
Hi,
after updating to the current beta i realized, that the color calibration assistant for use with Kosi is gone. Is this a bug or on purpose?

**Comment by awawa-dev** [comment]
On purpose during the web interface refactoring quite a long time ago. If someone wants to create a new assistant from scratch using newer Bootstrap 5 and submit a PR, please do so, but I won't do it myself.
