### ISSUE TITLE
Config Issue with SK6812 RGBW

### ISSUE THREAD

**Issue by chikko80** [awawa-dev/HyperHDR#78]
I installed my brand new SK6812 today. Its an upgrade from my ws2801.

The SK6812 had an extreme lag with the HyperHDR default config, which was getting bigger and bigger. After about a minute, the lag was already 5-7 seconds. After 5 minutes, the lag was beyond 30 seconds.

I was able to solve the problem by importing the Hyperion Default Config and making all the settings again manually. At my first try I was still on Hyperbian and used HyperHDR as package installation.

After I only use HyperHDR anyway, I switched to the HyperHDR image as a test. With the default config I had the same problem there. It has constantly lag which became larger and larger.

I'm not sure what exactly, but something in the HyperHDR default config causes a massively increasing lag when a SK6812 Led Strip is plugged into GPIO 10 with SK6812Spi setting.

After the lag reappeared, I imported the Hyperion Default Config again and then everything worked fine.

The default config also worked with my old WS2801 without problems. But apparently something does not fit with the SK6812

**Comment by chikko80** [comment]
The smoothing was just to high for the sk6812 :)

**Comment by awawa-dev** [comment]
I suspected that the smoothing could be a factor as sometimes it happens when the led driver is slowing down the communication. But even with around 250 rgbw leds and using highspeed SPI (at least 2Mb) it should be enough to over 80fps. I would check SPI settings/speed anyway. And I always recommend using external ESP2866/ESP32 for WS2812/2813/6812 etc  ;)

**Comment by chikko80** [comment]
@awawa-dev Yes it was the smoothing. I have 300 LED's and decreased the smoothing from 80 to 70.. Now everything is working fine. Whats the advantage of using ESP2866/ESP32? I don't want WLED.. it fine for me too have it wired behind my tv

**Comment by awawa-dev** [comment]
OK, if it works for you then it's fine. I didn't suggests WLED but sometimes it's a problem for RPi to handle the sk6812 communication (it's a way different then good old ws2801 you used and timings are critical) and usage of application such as HyperHDR at same time.

**Comment by chikko80** [comment]
okay, ill see how the leds work.. so far I have not noticed anything negative!

I am working on a solution for switching the HDR<->SDR Mapping over your API automatically for the FireTv Stick.
Would you be interested in adding this to your blog? i think this is interesting for a lot of people out there, since not everyone owns a denon amplifier. In fact I think a lot of people just have a fire tv stick on their tv.

**Comment by awawa-dev** [comment]
Would be great :) BTW I also have the FireTv Stick 4k but didn't have a time to configure it yet.

**Comment by chikko80** [comment]
I have an idea and in theory it should be possible. I will sit down later and see if it works as I imagine. I'll contact you if the whole thing works :)

**Comment by chikko80** [comment]
@awawa-dev 
I have a quick question. Why is hyperhdr running on full cpu ressources (after i shutdown my TV and FireTV Stick) despite my log shows me:

2021-07-02T20:14:13.001Z [V4L2:/DEV/VIDEO0] (INFO) Signal lost
2021-07-02T20:14:14.929Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:252:setInputImage()) Priority 240 is now inactive
2021-07-02T20:14:14.931Z [HYPERHDR] (DEBUG) (PriorityMuxer.cpp:378:setCurrentTime()) Set visible priority to 255
2021-07-02T20:14:14.932Z [HYPERHDR] (DEBUG) (HyperHdrInstance.cpp:550:handlePriorityChangedLedDevice()) priority[255], previousPriority[240]
2021-07-02T20:14:14.932Z [HYPERHDR] (ERROR) No source left -> switch LED-Device off

**Comment by awawa-dev** [comment]
Seems the signal detection is working. It shut down the hyperhdr instance ('Signal lost') but it still needs to capture & partially process frames from the USB grabber just to know when it's time to wake up when the signal is back.

**Comment by chikko80** [comment]
Yeah i understand, buts it needs full ressources. If i watch a movie and have my capture resolution at 1080p my raspberry is at about 180-200% CPU (top command).. And if the fire tv stick is sleeping and there is no signal, the cpu is still used 180-200%.. Thats not quite efficient in my perspective.. It would be smart to reduce the resolution automatically to something like 720p and 5fps or lower.

Or am I missing something here? why is the cpu load still as high as in life mode?

**Comment by awawa-dev** [comment]
Video processing takes most of the CPU resources why HyperHDR is running. 180-200% (out of 400%) for 1080p is quite normal result. There is a possible solution to use API and remotely turn on/off video components (just to be warned that the command name will be probably changed/refactored in the incoming version). Or to reduce grabber's 1080p to some lower resolution or to turn 'quarter of frame mode' in the grabber.

**Comment by chikko80** [comment]
Do you provide some kind of documentation for the API?

**Comment by awawa-dev** [comment]
For now you can use Hyperion NG JSON-RPC API documentation. Forking process takes some and the HyperHDR's installation/configuration manual had higher priority till now. But as the json API will be changed in the next version the new documentation for HyperHDR API will be provided too.

**Comment by chikko80** [comment]
Just a great Project i appreciate it!

Quick update:
My solution for the fire tv stick is basically working, but the advanced options menu has to run on the screen all the time, so this is not a viable solution. My plan was to read the codec information in the background and switch based on that. Unfortunately the codec information can only be read via adb when the advanced options menu is actively running...

Hopefully i can figure out another solution, but this approach is done for now..
