### ISSUE TITLE
Ubuntu 20.04 LTS repository issue

### ISSUE THREAD

**Issue by ArturNadolski** [awawa-dev/HyperHDR#784]
#### Steps to reproduce
type -p curl >/dev/null || sudo apt install curl -y
curl -fsSL https://awawa-dev.github.io/hyperhdr.public.apt.gpg.key | sudo dd of=/usr/share/keyrings/hyperhdr.public.apt.gpg.key \
&& sudo chmod go+r /usr/share/keyrings/hyperhdr.public.apt.gpg.key \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://awawa-dev.github.io $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperhdr.list > /dev/null \
&& sudo apt update \
&& sudo apt install hyperhdr -y

#### What is expected?
Installation of HyperHDR from repository.

#### What is actually happening?
Err:6 https://awawa-dev.github.io focal Release
  404  Not Found [IP: 185.199.111.153 443]
Reading package lists... Done
E: The repository 'https://awawa-dev.github.io focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

#### System

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
Hardware: Radxa Zero

**Comment by awawa-dev** [comment]
Hi
It's in the changelog as it was a new feature. Due to limited resources we do not support legacy Ubuntu in the APT repository. https://github.com/awawa-dev/HyperHDR/pull/522 You can try installing the "Debian bullseye" DEB installer manually: it should detect whether glibc version 20.04 is sufficient.
