### ISSUE TITLE
Captured video  - problems with colors

### ISSUE THREAD

**Issue by ArturNadolski** [awawa-dev/HyperHDR#789]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

https://pastebin.com/wY9HjHfn
#### Steps to reproduce
RPI4B+AWA_SPI+MS2130+Feintech VSP01222
#### What is expected?
Real colors
#### What is actually happening?
Captured video has only blue and yellow colors
#### System

https://pastebin.com/nwd50gdQ
![shot193539](https://github.com/awawa-dev/HyperHDR/assets/20038314/0db9012d-b16e-4bd5-8955-44cfe3fa7090)
![IMG_20240309_193539042_HDR](https://github.com/awawa-dev/HyperHDR/assets/20038314/434027e5-5984-4365-93ad-f607d758ce69)

**Comment by awawa-dev** [comment]
Hi
Interesting but I don't see any connection to HyperHDR here. In fact quite interesting sepia effect ;) Maybe you tuned-up LUT table or it's broken?
Connect the grabber to USB2.0 port, set MJPEG in the grabber configuration and disable tone mapping.
