### ISSUE TITLE
Instance Capturing is not working > unlocked PC after about hours

### ISSUE THREAD

**Issue by kenny-nt** [awawa-dev/HyperHDR#794]
Here is the log:
[hyperHDR.log](https://github.com/awawa-dev/HyperHDR/files/14580824/hyperHDR.log)

#### Steps to reproduce
Locked PC at night > Leds go to idle state (black color)
In the morning, moving mouse for monitors turn on > Leds are on.
Unlock PC > Leds go to off and will not turn on screen capturing
![image](https://github.com/awawa-dev/HyperHDR/assets/46035468/e1a16df7-f596-4bd1-9237-13f4c9a2c582)

#### What is expected?
Screen Capturing will work again when system is unlocked
#### What is actually happening?
In logs, HyperHDR start DX grabber OK but leds are not on and there is no System Capturing in Remote Control

**Comment by awawa-dev** [comment]
Hi
Exactly what log says:
> ...
> 2024-03-13T08:32:30.573Z [DX11_SYSTEM:AUTO] (DxGrabber.cpp:796) AcquireNextFrame didn't return the frame. Just warning: the screen has not changed?
> 2024-03-13T08:32:30.621Z [DX11_SYSTEM:AUTO] (DxGrabber.cpp:796) AcquireNextFrame didn't return the frame. Just warning: the screen has not changed?

That's how DirectX capturing works at the core to reduce the load. User must made some change to the screen to force it to capture a new frame. Later if HyperHDR captures at least one frame it could process it again and again if new frame wont come. But after the grabber is restarted the buffer is empty so it's still wating at least for the first frame where user does some interaction with the desktop.

**Comment by awawa-dev** [comment]
I mean user must then do some interaction with the desktop to force DirectX to capture new frame because of the change. For example move mouse cursor or window. There is nothing else in the logs.

**Comment by kenny-nt** [comment]
Of course I use both of keyboard and mouse to interacting in both of screen when the pc unlocked. How could it be no frame?

**Comment by awawa-dev** [comment]
Did you try to click on some window and move it? Or bring context menu: right lick on the desktop for the monitor that is captured? If nothings happens then, check logs again. In my case `AcquireNextFrame didn't return the frame` always happen when the screen is not updated and goes away when I perform some intteraction (and capturing immediately return then automatically)

**Comment by kenny-nt** [comment]
> l
Of course yes. I unlocked my PC and doing lots of actions immediately... Example: open chrome, open email or start a game. And of course mouse was always being moved

**Comment by kenny-nt** [comment]
Yes, I read the log too, and don't know why HyperHDR lost Screen Capture. Even in Remote Control, I turn off and on System Screen Capture but not working > Must change Device to another Display, save and change back to current Display to make it work again. It happen with DP too not only HDMI.

**Comment by kenny-nt** [comment]
Still the same issue. Now it happed more and more
[log.txt](https://github.com/awawa-dev/HyperHDR/files/15368312/log.txt)
Before: Lock PC at night (about 21:00 - 01:00) > Log on at morning (about 8:00-9:00) Screen Grabber sometimes not work.
Now: The same and Screen Grabber do not work anymore. >>> I must Video Capturing > Software Screen Capture > Select another source > save > re - select Display 1 for working again.
Have test with just only 1 HDMI monitor and have the same issue. I must > select Automatic > save > select Display 1 again.

**Comment by awawa-dev** [comment]
The old rule still applies: in order for me to fix something, I must be able to repeat it myself. And since I have the development environment on a headless computer with any monitor attached, I can't help here. Unless something obvious appears in the logs, but the truncated ones here don't tell me anything, maybe something started happening earlier. If you can, check if you can achieve similar results by locking the session (on the local computer, windows key + L).
