### ISSUE TITLE
Device 'adalight' is disabled due to an error: 'Permission denied'

### ISSUE THREAD

**Issue by MrMurkin** [awawa-dev/HyperHDR#802]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

[log.log](https://github.com/awawa-dev/HyperHDR/files/14731247/log.log)

#### Steps to reproduce
![изображение](https://github.com/awawa-dev/HyperHDR/assets/62289125/2124c861-b7eb-41f7-8a3e-ae8f512cfd8b)

#### What is expected?

Rainbow

#### What is actually happening?

I'd like to know

#### System

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by awawa-dev** [comment]
Hi
Make sure your user belongs to dialout group and no other application is using that serial port at the same time.

**Comment by MrMurkin** [comment]
![изображение](https://github.com/awawa-dev/HyperHDR/assets/62289125/9d55bfee-aa0a-4526-99dc-88bc7e0d23eb)
ok, i'll check it later

**Comment by awawa-dev** [comment]
BTW I dont think /dev/ttyCH341USB0 is a valid com port. Maybe it's a driver issue or you are selecting wrong one? check the rights with ls -l /dev/ttyCH341USB0
