### ISSUE TITLE
XZ Utils has been banned!

### ISSUE THREAD

**Issue by DonaldTrump-2020** [awawa-dev/HyperHDR#811]
Currently XZ Utils has been closed due to a dangerous warning. Can you fix it?

Source: https://twitter.com/wdormann/status/1773753334710538746

**Comment by awawa-dev** [comment]
yes, I know https://github.com/awawa-dev/HyperHDR/tree/switch_xz 
HyperHDR was not affected as we used 5.4.3 before the attack, but they remove repository from github

**Comment by DonaldTrump-2020** [comment]
> XZ Utils

XZ Utils on github was deleted, so I cannot use its link

**Comment by awawa-dev** [comment]
https://github.com/awawa-dev/HyperHDR/pull/812

**Comment by DonaldTrump-2020** [comment]
it works bro! thank you so much!
