### ISSUE TITLE
Macos Not working

### ISSUE THREAD

**Issue by fanqyxl** [awawa-dev/HyperHDR#822]
#### Steps to reproduce
none
#### What is expected?
full install
#### What is actually happening?
mac os saying hyperhdr not supported on intel i7 with 128gb ram.
#### System

<img width="2047" alt="Screenshot 2024-04-11 at 19 19 30" src="https://github.com/awawa-dev/HyperHDR/assets/165182838/a933f34e-8a72-4eb0-95a9-586619ddad56">

**Comment by awawa-dev** [comment]
you try to use arm setup for your intel platform, no wonder it doesnt work. built it your self or use x86 setup from latest github action for example: https://github.com/awawa-dev/HyperHDR/actions/runs/8514125239 (Apple_macOS_x64_DMG_installer artifact)
