### ISSUE TITLE
WLED over network not working?

### ISSUE THREAD

**Issue by throwingbits** [awawa-dev/HyperHDR#83]
My SK6812 are not coloring up when using HyperHDR in combination with WLED 0.12 (connection made via network).
The grabber is working and and LED Layout is also configured.

Any ideas whats the problem? Is this a common issue / pitfall?

#### System
WLED 0.12
HyperHDR on Raspberry Pi 2
Installed via package manager

**Comment by awawa-dev** [comment]
Hi
Dont have any similar report so far but think it should help:
- try to ping WLED from Rpi, if it's not working then you have an explanation
- connect using USB cable Rpi 2 with WLED (adalight in HyperHDR), if it's not working then it's an WLED/hardware issues
Anyway, mandatory logs are missing and they could help in the case so closing.

**Comment by throwingbits** [comment]
Ping is working. Will try adalight. But I doubt that this is a hardware issue because I had hyperion.ng installed before. And there my LEDs are controlled without problems.

Just wanted to try HyperHDR because I have some problemws regarding HDR content. Will report back. Thank you

**Comment by awawa-dev** [comment]
If your setup worked before then check your logs first please. Maybe it's a misconfiguration especially if you used config imported from Hyperion ng: it's not compatible any longer with HyperHDR.
