### ISSUE TITLE
Describe the process of color calibration

### ISSUE THREAD

**Issue by asm0dey** [awawa-dev/HyperHDR#853]
#### What problem does this feature solve?

Currently it's not clear how to match my wled + led strip colors to the colors on my TV 

#### What does the proposed API look like?

It might be just a page in docs somewhere, like this one
https://github.com/AEtHeLsYn/hyperion/wiki/Color-Calibration. I imagine it's somewhat outdated, given it's for another product and 8 years old. 

#### How should this be implemented in your opinion?

But in a perfect world it's should be android app, of course, that looks at pictures of TV with ambilight enabled and changes settings on the fly

#### Are you willing to work on this yourself?

I'm not sure. I can help a bit, but I'll not sure how

**Comment by asm0dey** [comment]
I think the most important part is not having a "perfect white", but having colors matching TV as close as possible. My TV is constantly running is the "Night shift" or whatever this thing is called when the level of blues is lower than it should be.

So yes, my goal is not to make the colors pleasant, my goal is to make the match TV's colors as good as possible to have this "augmentation" effect. And this thingie, I think, can even be automated, at least for SDR.

**Comment by awawa-dev** [comment]
> At least for static images
> ...
> my goal is to make the match TV's colors

So these are exactly the cases no. 1 and 3 described by me :wink: As I have already explained, from my point of view it is unrealistic and I will not undertake it myself, but I am open to suggestions along with their possible implementation in the code if changes are needed. So I leave this request feature opened for others.

**Comment by asm0dey** [comment]
I think the current code shouldn't be touched at all, it's more a question of an external android/iOS application, that takes photos and tunes parameters accordingly. Contrary to the human eye phone can catch differences and the tune settings very quickly. 

But I get your point, thanks for the answer
