### ISSUE TITLE
Add support for Skydimo USB lights

### ISSUE THREAD

**Issue by flobere** [awawa-dev/HyperHDR#934]
## Feature request

Add support for Skydimo USB lights

#### What problem does this feature solve?

compatibility with Skydimo lights- simple plug and play USB devices which can be had cheaply from Aliexpress. They are apparently similar to the Adalight implementation.

#### What does the proposed API look like?

Skydimo device support in LED controller config

#### How should this be implemented in your opinion?

I have no coding knowledge, but a feature request outlining details on the hardware and possible implementation was raised on the hyperion.ng project [here](https://github.com/hyperion-project/hyperion.ng/issues/1764), and later [added](https://github.com/hyperion-project/hyperion.ng/pull/1765) (i'm unaware if linking to this is helpful or good practice, i'm new to using github)

#### Are you willing to work on this yourself?

No, but will happily donate to the project

**Comment by jontstaz** [comment]
Out of interest, have you tried using them just by using the Adalight config? I'm considering buying a few sets of these for my monitors but I run Arch Linux and the Skydimo software only supports Windows.

**Comment by flobere** [comment]
No luck with the adalight config. It's unfortunate because they're a great AIO product. hyperion.ng works out of the box (effects, colour etc), but has no support for wayland/ pipewire screen capture and no intention of adding it in the foreseeable future. This project neatly supports it, but no support for the skidimo lights yet.

**Comment by awawa-dev** [comment]
If you can provide documentation describing the protocol, then I think there would be a good chance to implement it. But I won't blindly copy and paste code from Hyperion. No official protocol documentation => the product is not as good as one might think and unless it's super special, there's no point in risking reverse engineering.

**Comment by flobere** [comment]
thanks for the reply. I only praise the product from a layperson/consumer standpoint- it's affordable, cleanly packaged and plug-and-play. Like any of the fine blackboxed wonders on aliexpress or temu, I doubt technical data is forthcoming unless reverse engineered. the linked comment made it sound like more of a matter of adding a tweaked adalight entry than reinventing the wheel, though.

<details><summary>said comment</summary>It is basically Adalight but Bytes 1 2 and 3 are "Ada", Bytes 4 and 5 are blank (0x00), Byte 6 is Led Count

Exemple for 65 leds:

Skydimo: Ada..A.......................................................... Hex: 41 64 61 00 00 41 00 00 00 ...

Hyperion: Ada.@........................................................... Hex: 41 64 61 00 40 15 00 00 00 ...</details>

**Comment by awawa-dev** [comment]
a loose note related to the topic looking at this hack: the participation of Chinese engineers in modifying the Adalight protocol consisted in completely removing the only mechanism that provided any kind of data consistency check (CRC for header), i.e. they basically broke it completely. However, I don't have these LEDs, so it would be hard to implement this example of bad engineering blindly. If someone is willing and will implement and test it, I have nothing against it.

**Comment by awawa-dev** [comment]
@flobere You can test the installer from here: https://github.com/awawa-dev/HyperHDR/actions/runs/11631638898 to check out if  anything come of it. The lack of any CRC creates ideal conditions for the protocol to completely desynchronize at some point, and whether it will happen is another matter.

**Comment by flobere** [comment]
working fine on fedora, just need to change the baudrate to 115200. I need to familiarize myself with the pipewire capture but seems to be working (with 1 sec delay/refresh) out of the box.

Let me know if there's any further testing I can do. Thanks very much for implementing this

**Comment by awawa-dev** [comment]
>  just need to change the baudrate to 115200. 

That's very, very slow. Check if you have dropped frame on the main page with statistics. Probably you will have to reduce LED refresh rate. How many LEDs you have? I'm guessing there's an Arduino inside... I wonder if it could be replaced with something ;-) Try a speed of 460800, maybe it'll work.

**Comment by flobere** [comment]
it's 65 leds / 27" version. After playing with configs i'd say that yeah, i'd probably replace it if i was any more invested in tinkering. about 17000 baud is the limit, and i can get 10->33 fps with no dropped frames. The latency is just good enough for watching video/ screen capture without distraction. Overall, easily worth the 20USD but with limitations.

Thanks again. I should close this issue now, yeah? I also wanted to check if it's known behaviour that the 1 second delay/refresh rate happens whenever the settings screen is in a background tab, minimised, or on another desktop group (KDE 6x fedora). I'll open another issue for this if it's a novel issue- i just can't find it discussed elsewhere.

**Comment by awawa-dev** [comment]
Web browser? that shouldn't have any effect on HyperHDR since it's a standalone app. If it's portal/pipewire and it's confirmed, then there's probably nothing you can do: wayland and screen capture are unfortunately questionable solutions, and some parts of the capture implementation may differ between desktops (KDE has always lagged behind in my experience). Hard to say.

**Comment by tetskiy** [comment]
> Из интереса, вы пробовали использовать их просто с помощью конфигурации Adalight? Я подумываю о покупке нескольких таких комплектов для своих мониторов, но я использую Arch Linux, а программное обеспечение Skydimo поддерживает только Windows.

Мне удалось написать скрипт в ~160 строк, который отлично реализует эффект AmbiLight на Linux. Использую ленту skydimo на 54 светодиода.

**Comment by GregFedy** [comment]
> > Из интереса, вы пробовали использовать их просто с помощью конфигурации Adalight? Я подумываю о покупке нескольких таких комплектов для своих мониторов, но я использую Arch Linux, а программное обеспечение Skydimo поддерживает только Windows.
> 
> Мне удалось написать скрипт в ~160 строк, который отлично реализует эффект AmbiLight на Linux. Использую ленту skydimo на 54 светодиода.

Could you provide it?
