### ISSUE TITLE
HDR to SDR tone mapping and LUT file - questions for better understanding

### ISSUE THREAD

**Issue by pandel** [awawa-dev/HyperHDR#94]
Hi!

The last days I am tinkering with the grabber and image processing sections of HyperHDR to get my LED colors as accurate as possible.

My setup:
- Hisense U8QF TV (4k)
- Marantz 5015 AVR (TV on main out, 8K-Passthrough, 4K@120 Hz)
- Wisfox Grabber (2109)
- ezcoo HDMI 1x2 4k 60Hz Splitter
- SK6812 RGBNW
- HyperHDR running under Windows 10

**LUT:**
Regarding the description I used HyperHDR's screenshot feature to take a picture of the current TV screen, uploaded it to the LUT generator and tried to optimize the colors. Sadly, any LUT file I generated made it worse. Too much color, browns become hard yellow-redish, reds turn out mostly pink, and so on. I always had to turn off the 'HDR to SDR...' parameter to make it better.

**Image Processing:**
Then I tried to tinker with the color values in the image processing tab. First I searched for a decent calibration video on Youtube and made some small corrections. These corrections had a small positive impact on color accuracy, but especially in dark areas sometimes the LEDs freak out a little bit. Take a film like 'Underworld: Rise of the Lycans' which is mostly dark, color processing seems to get a little tricky.

**Conclusion:**
At the moment, I disabled 'HDR to SDR...', raised the hardware hue to +4 and set all colors in image processing to default values and that seems to get most colors accurate - despite the errors in dark areas.

**So, my questions are:**
- Which steps should be taken in which order to get the most out of LUT and image processing regarding color accuracy?
- Are there any decent calibration images / videos which would help in this regard?
- Is there any HowTo regarding the LUT generator? I am still setting values with no real idea what I am doing there. What are those Hardle/Reinhard/BT.2020 to... things, etc... Is there an example (video) on how to use it correctly to really achieve a better image quality?

As a side note: I always read about flat colors while not using 'HDR to SDR...', but my LED colors are somehow always bright and shiny, I do not need even more colors.

Sorry for the long post, but I'd really like to understand how this all fits together to be able to change the right parameters.

Regards,
Holger

**Comment by awawa-dev** [comment]
Probably you have SDR image already, maybe it's your AVR done it's job as some can do HDR->SDR or the grabber is receiving non-HDR signal. The only grabber that I know that can do partial HDR->SDR tone mapping is Ezcap 320. Grabbers based only on MS 2109 can't do it.

**Comment by pandel** [comment]
I forgot something really important, sorry: my ezcoo Splitter is set to downscale 4k to 1080p. Perhaps this does the trick even though the product description says that the device isn't able to convert HDR to SDR...

**Comment by awawa-dev** [comment]
I doubt. 1080p also supports HDR. I would check if the signal that comes to/out from the ezcoo is in fact HDR.
