### ISSUE TITLE
SDR screen capture overexposed when SDR content brightness is bit higher than the mnimum value

### ISSUE THREAD

**Issue by ananyosen** [awawa-dev/HyperHDR#942]
#### Logs
https://pastebin.com/yJfjXC5S

#### Steps to reproduce
Enable HDR in windows, and increase SDR Content Brightness in HDR settings. Visit https://www.whitescreen.online/pink-screen/ and check the live capture.

#### What is expected?
HyperHDR to capture colors correctly
#### What is actually happening?
HyperHDR screen grabs are overexposed. Website I am using to test https://www.whitescreen.online/pink-screen/ . As a result, LEDs also show white in these cases.

Screen capture when the setting is at minimum 
![image](https://github.com/user-attachments/assets/63617fee-ba34-4e5e-8a08-fcc1d01822ed)

Screen Capture when the slider value is increased
![image](https://github.com/user-attachments/assets/9a139306-d5f6-4ba1-b196-419f02c91086)

The pink color clips.  The settings "HDR to SDR tone mapping" and "HDR brightness correction" have no visible effect on this problem. I am using an OLED monitor which is capable of true HDR and shows proper colors, regardless of the SDR Content Brightness setting.
#### System

```
HyperHDR Server: 
- Build:           (HEAD detached at v20.0.0.0) (awawa-dev-9e960c9/52f12b4-1711236142)
- Build time:      Mar 23 2024 23:28:49
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0
- UI Lang:         auto (BrowserLang: en-US)
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 11 Version 23H2
- Architecture:   x86_64
- CPU Model:      13th Gen Intel(R) Core(TM) i7-13700K
- Kernel:         winnt (10.0.22631 (WS: 64))
- Qt Version:     6.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0 
```

**Comment by awawa-dev** [comment]
This is not a bug: such fancy Windows 11 features that interfered with default color management were never supported, as in this case https://github.com/awawa-dev/HyperHDR/discussions/924 If adjusting the brightness level in HyperHDR DirectX configuration panel doesn't help, then I don't currently see a way to work around this issue.
