### ISSUE TITLE
HyperHDR won't start on Fedora 41

### ISSUE THREAD

**Issue by vogonwann** [awawa-dev/HyperHDR#943]
#### Steps to reproduce
Tried to start `hyperhdr`
#### What is expected?
`hyperhdr starts`
#### What is actually happening?
Nothing happens
#### System

Cannot access web interface

this is the log

```sep 24 10:28:08 fedex audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=hyperhdr@wann comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
sep 24 10:28:08 fedex hyperhdr[99420]: /usr/bin/hyperhdr: /usr/share/hyperhdr/bin/../lib/libcrypto.so.3: version `OPENSSL_3.2.0' not found (required by /lib64/libssl.so.3)
sep 24 10:28:08 fedex systemd[1]: hyperhdr@wann.service: Main process exited, code=exited, status=1/FAILURE
sep 24 10:28:08 fedex systemd[1]: hyperhdr@wann.service: Failed with result 'exit-code'.
sep 24 10:28:08 fedex audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=hyperhdr@wann comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
sep 24 10:28:10 fedex systemd[1]: hyperhdr@wann.service: Scheduled restart job, restart counter is at 2187.```
sep 24 10:28:10 fedex systemd[1]: Started hyperhdr@wann.service - HyperHdr ambient light systemd service  for user wann.

**Comment by vogonwann** [comment]
forgot to mention that `openssl-libs` package is installed. Version >= 3.2.0

**Comment by awawa-dev** [comment]
HI
Fedora 41 still in beta phase, currently we offer installers for Fedora 40 only. Did you try to compile HyperHDR yourself?

**Comment by vogonwann** [comment]
No I didn't. I'll try and report back.

**Comment by awawa-dev** [comment]
OK, you can also try HyperHDR v21 installer ( ex. https://github.com/awawa-dev/HyperHDR/actions/runs/11392201769 ) because some things has changed. In your case I suspect the packaging problem, source RPATH of depended libraries more specifically.

**Comment by awawa-dev** [comment]
> OK, you can also try HyperHDR v21 installer ( ex. https://github.com/awawa-dev/HyperHDR/actions/runs/11392201769 ) because some things has changed. 

Seems this installer works fine both on Fedora 40 and 41. the service must be enabled for GUI system otherwise run HyperHDR as a GUI app from the menu.
![obraz](https://github.com/user-attachments/assets/9898c80e-8a5f-4913-ba4e-a9fd1a98444d)

**Comment by awawa-dev** [comment]
Please reopen the issue if the problem recurs in the latest HyperHDR 21 version on the newer stable release of Fedora 41. So far it seems to work OK on Fedora 41 beta.
