### ISSUE TITLE
Make adjustments to specific id using JSON API seems not work anymore in HyperHDR 20

### ISSUE THREAD

**Issue by ld892012** [awawa-dev/HyperHDR#953]
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

[LOG](https://pastebin.com/iW7hdbeg)

#### Steps to reproduce
For example, as link :
`
http://localhost:8090/json-rpc?request=%7B%22command%22:%22adjustment%22,%22adjustment%22:%7B%22id%22:%22Name%22,%22classic_config%22:true,%22luminanceGain%22:1%7D%7D
`

#### What is expected?
Change Luminance Gain of id "Name" to "1"

#### What is actually happening?
It seems to change nothing in this instance

#### System

```
HyperHDR Server: 
- Build:           (HEAD detached at v20.0.0.0) (awawa-dev-9e960c9/52f12b4-1711236142)
- Build time:      Mar 23 2024 23:49:20
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0
- UI Lang:         auto (BrowserLang: fr)
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Armbian 22.08.2 Bullseye
- Architecture:   arm64
- Kernel:         linux (5.15.69-sunxi64 (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0 
```

I have tried in v19 without any problems, maybe I just use a depreciated feature

**Comment by awawa-dev** [comment]
Hi
Could you upload the json backup of your configuration?

**Comment by ld892012** [comment]
Here it is :
[HyperHDR-20.0.0.0-Backup-2024-10-05.json](https://github.com/user-attachments/files/17267289/HyperHDR-20.0.0.0-Backup-2024-10-05.json)

Thanks for your quick response

**Comment by ld892012** [comment]
I just have tested with a portable install on my PC with one instance of 2 LED and that gives me the same strange behavior, whether I change the id of the first or second LED, it's always the first LED that is modified.

I just set "255,255,255" color and set luminance of id "Second" to 0 then to 1 with this following link :
`http://localhost:8090/json-rpc?request={%22command%22:%22adjustment%22,%22adjustment%22:{%22id%22:%22Second%22,%22classic_config%22:true,%22luminanceGain%22:0}}`

I give you this new config, logs, system info and LED file (this is more light comparing to my huge config) :
[Logs.txt](https://github.com/user-attachments/files/17281844/Logs.txt)
[Config.json](https://github.com/user-attachments/files/17281845/Config.json)
[LED_instance.txt](https://github.com/user-attachments/files/17281853/LED_instance.txt)
```
HyperHDR Server: 
- Build:           (HEAD detached at v20.0.0.0) (awawa-dev-9e960c9/52f12b4-1711236142)
- Build time:      Mar 23 2024 23:28:49
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         20.0.0.0
- UI Lang:         en (BrowserLang: fr)
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 11 Version 22H2
- Architecture:   x86_64
- CPU Model:      11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
- Kernel:         winnt (10.0.22621 (WS: 64))
- Qt Version:     6.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0 
```

Thanks in advance for your help

**Comment by awawa-dev** [comment]
Hi
This functionality was lost when the JSON API (now HyperAPI) was almost completely rewritten on the backend side. Thanks for the report. The fix is ​​available in this PR: https://github.com/awawa-dev/HyperHDR/pull/956 (and the setups in the Github Action).

**Comment by ld892012** [comment]
OK thank you for your work, a fix is now here so i will close this issue
